IF
    True()
THEN
    RESPONSE #100
        CutSceneId(Player1)
        MoveViewObject(Myself,INSTANT)
		Wait(2)
		CreateCreature("C0CR#GOR",[1144.2348],S)
		FaceObject("C0CR#GOR")
		ActionOverride("C0CR#GOR",MoveToPoint([1367.2605]))
		ActionOverride("C0CR#GOR",SmallWait(5))
		ActionOverride("C0CR#GOR",FaceObject(Player1))
		ActionOverride("C0CR#GOR",Wait(2))
		ActionOverride("C0CR#GOR",StartDialogueNoSet(Player1))
END
