IF
    True()
THEN
    RESPONSE #100
        CutSceneId("IMOEN")
        GivePartyAllEquipment()
        LeaveParty()
		GiveItemCreate("POTN08","imoen",3,1,0)
		GiveItemCreate("POTN14","imoen",1,1,0)
		GiveItemCreate("WAND12","imoen",10,1,0)
		GiveItemCreate("BOW05","imoen",1,1,0)
		GiveItemCreate("AROW01","imoen",40,1,0)
		ActionOverride("imoen",SetItemFlags("WAND12",IDENTIFIED,TRUE))
		SmallWait(1)
		EscapeAreaMove("AR2700",3140,3681,S)
END
