// Divine spells

// Level 1

TEXT_SPRINT CLERIC_BLESS ~SPPR101~
TEXT_SPRINT CLERIC_COMMAND ~SPPR102~
TEXT_SPRINT CLERIC_CURE_LIGHT_WOUNDS ~SPPR103~
TEXT_SPRINT CLERIC_DETECT_EVIL ~SPPR104~
TEXT_SPRINT CLERIC_ENTANGLE ~SPPR105~
TEXT_SPRINT CLERIC_MAGIC_STONE ~SPPR106~
TEXT_SPRINT CLERIC_PROTECT_FROM_EVIL ~SPPR107~
TEXT_SPRINT CLERIC_REMOVE_FEAR ~SPPR108~
TEXT_SPRINT CLERIC_SANCTUARY ~SPPR109~
TEXT_SPRINT CLERIC_SHILLELAGH ~SPPR110~
TEXT_SPRINT CLERIC_ARMOR_OF_FAITH ~SPPR111~
TEXT_SPRINT CLERIC_DOOM ~SPPR113~
TEXT_SPRINT CLERIC_SPIRIT_WARD ~SPPR150~

// Level 2

TEXT_SPRINT CLERIC_AID ~SPPR201~
TEXT_SPRINT CLERIC_BARKSKIN ~SPPR202~
TEXT_SPRINT CLERIC_CHANT ~SPPR203~
TEXT_SPRINT CLERIC_CHARM_PERSON ~SPPR204~
TEXT_SPRINT CLERIC_FIND_TRAPS ~SPPR205~
TEXT_SPRINT CLERIC_FLAME_BLADE ~SPPR206~
TEXT_SPRINT CLERIC_GOOD_BERRIES ~SPPR207~
TEXT_SPRINT CLERIC_HOLD_PERSON ~SPPR208~
TEXT_SPRINT CLERIC_KNOW_ALIGNMENT ~SPPR209~
TEXT_SPRINT CLERIC_RESIST_FIRE ~SPPR210~
TEXT_SPRINT CLERIC_SILENCE_15_FOOT ~SPPR211~
TEXT_SPRINT CLERIC_SLOW_POISON ~SPPR212~
TEXT_SPRINT CLERIC_SPIRITUAL_HAMMER ~SPPR213~
TEXT_SPRINT CLERIC_DRAW_UPON_HOLY_MIGHT ~SPPR214~
TEXT_SPRINT CLERIC_WRITHING_FOG ~SPPR250~

// Level 3

TEXT_SPRINT CLERIC_ANIMATE_DEAD ~SPPR301~
TEXT_SPRINT CLERIC_CALL_LIGHTNING ~SPPR302~
TEXT_SPRINT CLERIC_DISPEL_MAGIC ~SPPR303~
TEXT_SPRINT CLERIC_GLYPH_OF_WARDING ~SPPR304~
TEXT_SPRINT CLERIC_HOLD_ANIMAL ~SPPR305~
TEXT_SPRINT CLERIC_PROTECTION_FROM_FIRE ~SPPR306~
TEXT_SPRINT CLERIC_REMOVE_CURSE ~SPPR307~
TEXT_SPRINT CLERIC_REMOVE_PARALYSIS ~SPPR308~
TEXT_SPRINT CLERIC_INVISIBILITY_PURGE ~SPPR309~
TEXT_SPRINT CLERIC_MISCAST_MAGIC ~SPPR310~
TEXT_SPRINT CLERIC_RIGID_THINKING ~SPPR311~
TEXT_SPRINT CLERIC_STRENGTH_OF_ONE ~SPPR312~
TEXT_SPRINT CLERIC_HOLY_SMITE ~SPPR313~
TEXT_SPRINT CLERIC_UNHOLY_BLIGHT ~SPPR314~
TEXT_SPRINT CLERIC_CURE_MEDIUM_WOUNDS ~SPPR315~
TEXT_SPRINT CLERIC_CURE_DISEASE ~SPPR317~
TEXT_SPRINT CLERIC_ZONE_OF_SWEET_AIR ~SPPR318~
TEXT_SPRINT CLERIC_SUMMON_INSECTS ~SPPR319~
TEXT_SPRINT CLERIC_SPIRITUAL_CLARITY ~SPPR350~

// Level 4

TEXT_SPRINT CLERIC_CURE_SERIOUS_WOUNDS ~SPPR401~
TEXT_SPRINT CLERIC_ANIMAL_SUMMONING_1 ~SPPR402~
TEXT_SPRINT CLERIC_FREE_ACTION ~SPPR403~
TEXT_SPRINT CLERIC_NEUTRALIZE_POISON ~SPPR404~
TEXT_SPRINT CLERIC_MENTAL_DOMINATION ~SPPR405~
TEXT_SPRINT CLERIC_DEFENSIVE_HARMONY ~SPPR406~
TEXT_SPRINT CLERIC_PROTECTION_FROM_LIGHTNING ~SPPR407~
TEXT_SPRINT CLERIC_PROTECTION_FROM_EVIL_10_FOOT ~SPPR408~
TEXT_SPRINT CLERIC_DEATH_WARD ~SPPR409~
TEXT_SPRINT CLERIC_CALL_WOODLAND_BEINGS ~SPPR410~
TEXT_SPRINT CLERIC_POISON ~SPPR411~
TEXT_SPRINT CLERIC_HOLY_POWER ~SPPR412~
TEXT_SPRINT CLERIC_NEGATIVE_PLANE_PROTECTION ~SPPR413~
TEXT_SPRINT CLERIC_CAUSE_SERIOUS_WOUNDS ~SPPR414~
TEXT_SPRINT CLERIC_FAR_SIGHT ~SPPR415~
TEXT_SPRINT CLERIC_CLOAK_OF_FEAR ~SPPR416~
TEXT_SPRINT CLERIC_LESSER_RESTORATION ~SPPR417~
TEXT_SPRINT CLERIC_SPIRIT_FIRE ~SPPR450~

// Level 5

TEXT_SPRINT CLERIC_ANIMAL_SUMMONING_2 ~SPPR501~
TEXT_SPRINT CLERIC_CURE_CRITICAL_WOUNDS ~SPPR502~
TEXT_SPRINT CLERIC_FLAME_STRIKE ~SPPR503~
TEXT_SPRINT CLERIC_RAISE_DEAD ~SPPR504~
TEXT_SPRINT CLERIC_TRUE_SIGHT ~SPPR505~
TEXT_SPRINT CLERIC_IRONSKIN ~SPPR506~
TEXT_SPRINT CLERIC_CHAMPIONS_STRENGTH ~SPPR507~
TEXT_SPRINT CLERIC_CHAOTIC_COMMANDS ~SPPR508~
TEXT_SPRINT CLERIC_MAGIC_RESISTANCE ~SPPR509~
TEXT_SPRINT CLERIC_CAUSE_CRITICAL_WOUNDS ~SPPR510~
TEXT_SPRINT CLERIC_SLAY_LIVING ~SPPR511~
TEXT_SPRINT CLERIC_GREATER_COMMAND ~SPPR512~
TEXT_SPRINT CLERIC_RIGHTEOUS_MAGIC ~SPPR513~
TEXT_SPRINT CLERIC_MASS_CURE ~SPPR514~
TEXT_SPRINT CLERIC_REPULSE_UNDEAD ~SPPR515~
TEXT_SPRINT CLERIC_PIXIE_DUST ~SPPR516~
TEXT_SPRINT CLERIC_INSECT_PLAGUE ~SPPR517~
TEXT_SPRINT CLERIC_RECALL_SPIRIT ~SPPR550~
TEXT_SPRINT ENEMY_CLERIC_SLAY_LIVING ~SPPR599~

// Level 6

TEXT_SPRINT CLERIC_AERIAL_SERVANT ~SPPR601~
TEXT_SPRINT CLERIC_ANIMAL_SUMMONING_3 ~SPPR602~
TEXT_SPRINT CLERIC_BLADE_BARRIER ~SPPR603~
TEXT_SPRINT CLERIC_CONJURE_ANIMALS ~SPPR604~
TEXT_SPRINT CLERIC_CONJURE_FIRE_ELEMENTAL ~SPPR605~
TEXT_SPRINT CLERIC_FIRE_SEEDS ~SPPR606~
TEXT_SPRINT CLERIC_HEAL ~SPPR607~
TEXT_SPRINT CLERIC_HARM ~SPPR608~
TEXT_SPRINT CLERIC_FALSE_DAWN ~SPPR609~
TEXT_SPRINT CLERIC_DOLOROUS_DECAY ~SPPR610~
TEXT_SPRINT CLERIC_WONDROUS_RECALL ~SPPR611~
TEXT_SPRINT CLERIC_BOLT_OF_GLORY ~SPPR612~
TEXT_SPRINT CLERIC_PHYSICAL_MIRROR ~SPPR613~
TEXT_SPRINT CLERIC_SOL_SEARING_ORB ~SPPR614~
TEXT_SPRINT CLERIC_SPIRITUAL_LOCK ~SPPR650~
TEXT_SPRINT NPC_BLADE_BARRIER ~SPPR698~
TEXT_SPRINT ENEMY_CLERIC_HARM ~SPPR699~

// Level 7

TEXT_SPRINT CLERIC_SHIELD_OF_THE_ARCHONS ~SPPR701~
TEXT_SPRINT CLERIC_CONJURE_EARTH_ELEMENTAL ~SPPR702~
TEXT_SPRINT CLERIC_GATE ~SPPR703~
TEXT_SPRINT CLERIC_NATURE_BEAUTY ~SPPR704~
TEXT_SPRINT CLERIC_FIRE_STORM ~SPPR705~
TEXT_SPRINT CLERIC_SYMBOL_FEAR ~SPPR706~
TEXT_SPRINT CLERIC_SUNRAY ~SPPR707~
TEXT_SPRINT CLERIC_FINGER_OF_DEATH ~SPPR708~
TEXT_SPRINT CLERIC_CONFUSION ~SPPR709~
TEXT_SPRINT CLERIC_HOLY_WORD ~SPPR710~
TEXT_SPRINT CLERIC_REGENERATE ~SPPR711~
TEXT_SPRINT CLERIC_RESURRECTION ~SPPR712~
TEXT_SPRINT CLERIC_RESTORATION ~SPPR713~
TEXT_SPRINT CLERIC_UNHOLY_WORD ~SPPR715~
TEXT_SPRINT CLERIC_CREEPING_DOOM ~SPPR717~
TEXT_SPRINT CLERIC_SYMBOL_STUN ~SPPR718~
TEXT_SPRINT CLERIC_SYMBOL_DEATH ~SPPR719~
TEXT_SPRINT CLERIC_EARTHQUAKE ~SPPR720~
TEXT_SPRINT CLERIC_ENERGY_BLADES ~SPPR721~
TEXT_SPRINT CLERIC_STORM_OF_VENGEANCE ~SPPR722~
TEXT_SPRINT CLERIC_ELEMENTAL_SWARM ~SPPR723~
TEXT_SPRINT CLERIC_GREATER_ELEMENTAL_SWARM ~SPPR724~
TEXT_SPRINT CLERIC_GLOBE_OF_BLADES ~SPPR725~
TEXT_SPRINT CLERIC_SUMMON_DEVA ~SPPR726~
TEXT_SPRINT CLERIC_SUMMON_FALLEN_DEVA ~SPPR727~
TEXT_SPRINT CLERIC_IMPLOSION ~SPPR728~
TEXT_SPRINT CLERIC_MASS_RAISE_DEAD ~SPPR729~
TEXT_SPRINT CLERIC_AURA_OF_FLAMING_DEATH ~SPPR730~
TEXT_SPRINT CLERIC_ELEMENTAL_TRANSFORMATION_FIRE ~SPPR731~
TEXT_SPRINT CLERIC_ELEMENTAL_TRANSFORMATION_EARTH ~SPPR732~
TEXT_SPRINT CLERIC_ETHER_GATE ~SPPR750~
TEXT_SPRINT CLERIC_ETHEREAL_RETRIBUTION ~SPPR751~

// Misc (e.g. Traps)

TEXT_SPRINT TRAP_DIRE_CHARM ~SPPR982~
TEXT_SPRINT TRAP_CONFUSION ~SPPR983~
TEXT_SPRINT TRAP_CHROMATIC_ORB ~SPPR984~
TEXT_SPRINT TRAP_FLAMESTRIKE ~SPPR985~
TEXT_SPRINT TRAP_MISCAST_MAGIC ~SPPR986~
TEXT_SPRINT TRAP_CALL_LIGHTNING ~SPPR987~
TEXT_SPRINT TRAP_SILENCE ~SPPR988~
TEXT_SPRINT TRAP_HOLD_PERSON ~SPPR989~
TEXT_SPRINT SHOAL_REVIVE ~SPPR999~

// Arcane spells

// Misc (e.g. Traps)

TEXT_SPRINT TRAP_FIREBALL ~SPWI001~
TEXT_SPRINT TRAP_LIGHTNING_BOLT ~SPWI002~
TEXT_SPRINT TRAP_MAGIC_MISSILE ~SPWI003~
TEXT_SPRINT TRAP_STINKING_CLOUD ~SPWI004~
TEXT_SPRINT TRAP_ARROW ~SPWI005~
TEXT_SPRINT TRAP_ARROW_SLAYING ~SPWI006~
TEXT_SPRINT TRAP_ARROW_ACID ~SPWI007~
TEXT_SPRINT TRAP_ARROW_BITING ~SPWI008~
TEXT_SPRINT TRAP_ARROW_DETONATION ~SPWI009~
TEXT_SPRINT TRAP_ARROW_DISPELLING ~SPWI010~
TEXT_SPRINT TRAP_ARROW_FIRE ~SPWI011~
TEXT_SPRINT TRAP_ARROW_ICE ~SPWI012~
TEXT_SPRINT TRAP_ARROW_PIERCING ~SPWI013~
TEXT_SPRINT TRAP_MONSTER_SUMMONING ~SPWI014~
TEXT_SPRINT TRAP_FROST ~SPWI015~
TEXT_SPRINT TRAP_CLOUDKILL ~SPWI016~
TEXT_SPRINT TRAP_MINOR_LIGHTNING_BOLT ~SPWI017~
TEXT_SPRINT TRAP_UNDERWATER_BITE ~SPWI020~
TEXT_SPRINT TRAP_HALLWAY_SPIKES ~SPWI021~
TEXT_SPRINT TRAP_MUCK ~SPWI022~
TEXT_SPRINT TRAP_SHADOW_DEATH ~SPWI023~
TEXT_SPRINT TRAP_GUILLOTINE ~SPWI024~
TEXT_SPRINT TRAP_LIGHTNING_ORB1 ~SPWI025~
TEXT_SPRINT TRAP_LIGHTNING_ORB2 ~SPWI026~
TEXT_SPRINT TRAP_LIGHTNING_ORB3 ~SPWI027~
TEXT_SPRINT WIZARD_CHAOS_VISUALS_ONLY ~SPWI050~
TEXT_SPRINT WIZARD_DISPEL_MAGIC_VISUALS_ONLY ~SPWI051~
TEXT_SPRINT WIZARD_POWER_WORD_SILENCE_VISUALS_ONLY ~SPWI052~
TEXT_SPRINT WIZARD_FLESH_TO_STONE_IGNORE_RESISTANCE ~SPWI053~
TEXT_SPRINT WIZARD_FINGER_OF_DEATH_IGNORE_RESISTANCE ~SPWI054~
TEXT_SPRINT WIZARD_DISINTEGRATE_IGNORE_RESISTANCE ~SPWI055~
TEXT_SPRINT WIZARD_DISINTEGRATE2_IGNORE_RESISTANCE ~SPWI056~

// Level 1

TEXT_SPRINT WIZARD_GREASE ~SPWI101~
TEXT_SPRINT WIZARD_ARMOR ~SPWI102~
TEXT_SPRINT WIZARD_BURNING_HANDS ~SPWI103~
TEXT_SPRINT WIZARD_CHARM_PERSON ~SPWI104~
TEXT_SPRINT WIZARD_COLOR_SPRAY ~SPWI105~
TEXT_SPRINT WIZARD_BLINDNESS ~SPWI106~
TEXT_SPRINT WIZARD_FRIENDS ~SPWI107~
TEXT_SPRINT WIZARD_PROTECTION_FROM_PETRIFICATION ~SPWI108~
TEXT_SPRINT WIZARD_IDENTIFY ~SPWI110~
TEXT_SPRINT WIZARD_INFRAVISION ~SPWI111~
TEXT_SPRINT WIZARD_MAGIC_MISSILE ~SPWI112~
TEXT_SPRINT WIZARD_PROTECTION_FROM_EVIL ~SPWI113~
TEXT_SPRINT WIZARD_SHIELD ~SPWI114~
TEXT_SPRINT WIZARD_SHOCKING_GRASP ~SPWI115~
TEXT_SPRINT WIZARD_SLEEP ~SPWI116~
TEXT_SPRINT WIZARD_CHILL_TOUCH ~SPWI117~
TEXT_SPRINT WIZARD_CHROMATIC_ORB ~SPWI118~
TEXT_SPRINT WIZARD_LARLOCH_MINOR_DRAIN ~SPWI119~
TEXT_SPRINT WIZARD_REFLECTED_IMAGE ~SPWI120~
TEXT_SPRINT WIZARD_FIND_FAMILAR ~SPWI123~
TEXT_SPRINT WIZARD_NAHALS_RECKLESS_DWEOMER ~SPWI124~
TEXT_SPRINT WIZARD_SPOOK ~SPWI125~

// Level 2

TEXT_SPRINT WIZARD_BLUR ~SPWI201~
TEXT_SPRINT WIZARD_DETECT_EVIL ~SPWI202~
TEXT_SPRINT WIZARD_DETECT_INVISIBILITY ~SPWI203~
TEXT_SPRINT WIZARD_HORROR ~SPWI205~
TEXT_SPRINT WIZARD_INVISIBILITY ~SPWI206~
TEXT_SPRINT WIZARD_KNOCK ~SPWI207~
TEXT_SPRINT WIZARD_KNOW_ALIGNMENT ~SPWI208~
TEXT_SPRINT WIZARD_LUCK ~SPWI209~
TEXT_SPRINT WIZARD_RESIST_FEAR ~SPWI210~
TEXT_SPRINT WIZARD_MELF_ACID_ARROW ~SPWI211~
TEXT_SPRINT WIZARD_MIRROR_IMAGE ~SPWI212~
TEXT_SPRINT WIZARD_STINKING_CLOUD ~SPWI213~
TEXT_SPRINT WIZARD_STRENGTH ~SPWI214~
TEXT_SPRINT WIZARD_WEB ~SPWI215~
TEXT_SPRINT WIZARD_AGANNAZAR_SCORCHER ~SPWI217~
TEXT_SPRINT WIZARD_GHOUL_TOUCH ~SPWI218~
TEXT_SPRINT WIZARD_VOCALIZE ~SPWI219~
TEXT_SPRINT WIZARD_POWER_WORD_SLEEP ~SPWI220~
TEXT_SPRINT WIZARD_RAY_OF_ENFEEBLEMENT ~SPWI221~
TEXT_SPRINT WIZARD_CHAOS_SHIELD ~SPWI222~
TEXT_SPRINT WIZARD_DEAFNESS ~SPWI223~
TEXT_SPRINT WIZARD_GLITTERDUST ~SPWI224~
TEXT_SPRINT CONTINGENCY_MIRROR_IMAGE ~SPWI298~

// Level 3

TEXT_SPRINT WIZARD_CLAIRVOYANCE ~SPWI301~
TEXT_SPRINT WIZARD_REMOVE_MAGIC ~SPWI302~
TEXT_SPRINT WIZARD_FLAME_ARROW ~SPWI303~
TEXT_SPRINT WIZARD_FIREBALL ~SPWI304~
TEXT_SPRINT WIZARD_HASTE ~SPWI305~
TEXT_SPRINT WIZARD_HOLD_PERSON ~SPWI306~
TEXT_SPRINT WIZARD_INVISIBILITY_10_FOOT ~SPWI307~
TEXT_SPRINT WIZARD_LIGHTNING_BOLT ~SPWI308~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_1 ~SPWI309~
TEXT_SPRINT WIZARD_NON_DETECTION ~SPWI310~
TEXT_SPRINT WIZARD_PROTECTION_FROM_NORMAL_MISSILES ~SPWI311~
TEXT_SPRINT WIZARD_SLOW ~SPWI312~
TEXT_SPRINT WIZARD_SKULL_TRAP ~SPWI313~
TEXT_SPRINT WIZARD_VAMPIRIC_TOUCH ~SPWI314~
TEXT_SPRINT WIZARD_WRAITH_FORM ~SPWI315~
TEXT_SPRINT WIZARD_DIRE_CHARM ~SPWI316~
TEXT_SPRINT WIZARD_GHOST_ARMOR ~SPWI317~
TEXT_SPRINT WIZARD_MINOR_SPELL_DEFLECTION ~SPWI318~
TEXT_SPRINT WIZARD_PROTECTION_FROM_FIRE ~SPWI319~
TEXT_SPRINT WIZARD_PROTECTION_FROM_COLD ~SPWI320~
TEXT_SPRINT WIZARD_SPELL_THRUST ~SPWI321~
TEXT_SPRINT WIZARD_DETECT_ILLUSION ~SPWI322~
TEXT_SPRINT WIZARD_HOLD_UNDEAD ~SPWI324~
TEXT_SPRINT WIZARD_MELF_METEOR ~SPWI325~
TEXT_SPRINT WIZARD_TRUE_DISPEL_MAGIC ~SPWI326~

// Level 4

TEXT_SPRINT WIZARD_CONFUSION ~SPWI401~
TEXT_SPRINT WIZARD_DIMENSION_DOOR ~SPWI402~
TEXT_SPRINT WIZARD_FIRE_SHIELD_BLUE ~SPWI403~
TEXT_SPRINT WIZARD_ICE_STORM ~SPWI404~
TEXT_SPRINT WIZARD_IMPROVED_INVISIBILITY ~SPWI405~
TEXT_SPRINT WIZARD_MINOR_GLOBE_OF_INVULNERABILITY ~SPWI406~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_2 ~SPWI407~
TEXT_SPRINT WIZARD_STONE_SKIN ~SPWI408~
TEXT_SPRINT WIZARD_CONTAGION ~SPWI409~
TEXT_SPRINT WIZARD_REMOVE_CURSE ~SPWI410~
TEXT_SPRINT WIZARD_EMOTION_HOPELESSNESS ~SPWI411~
TEXT_SPRINT WIZARD_GREATER_MALISON ~SPWI412~
TEXT_SPRINT WIZARD_OTILUKES_RESILIENT_SPHERE ~SPWI413~
TEXT_SPRINT WIZARD_SPIRIT_ARMOR ~SPWI414~
TEXT_SPRINT WIZARD_POLYMORPH_OTHER ~SPWI415~
TEXT_SPRINT WIZARD_POLYMORPH_SELF ~SPWI416~
TEXT_SPRINT WIZARD_ENCHANTED_WEAPON ~SPWI417~
TEXT_SPRINT WIZARD_FIRE_SHIELD_RED ~SPWI418~
TEXT_SPRINT WIZARD_SECRET_WORD ~SPWI419~
TEXT_SPRINT WIZARD_MINOR_SEQUENCER ~SPWI420~
TEXT_SPRINT WIZARD_TELEPORT_FIELD ~SPWI421~
TEXT_SPRINT WIZARD_SPIDER_SPAWN ~SPWI423~
TEXT_SPRINT WIZARD_FAR_SIGHT ~SPWI424~
TEXT_SPRINT WIZARD_EYE ~SPWI425~
TEXT_SPRINT WIZARD_POLYMORPH_NATURAL_FORM ~SPWI490~
TEXT_SPRINT WIZARD_POLYMORPH_FLIND ~SPWI493~
TEXT_SPRINT WIZARD_POLYMORPH_OGRE ~SPWI494~
TEXT_SPRINT WIZARD_POLYMORPH_SPIDER ~SPWI495~
TEXT_SPRINT WIZARD_POLYMORPH_MUSTARD_JELLY ~SPWI496~
TEXT_SPRINT WIZARD_POLYMORPH_BROWN_BEAR ~SPWI497~
TEXT_SPRINT WIZARD_POLYMORPH_BLACK_BEAR ~SPWI498~
TEXT_SPRINT WIZARD_POLYMORPH_WOLF ~SPWI499~

// Level 5

TEXT_SPRINT WIZARD_ANIMATE_DEAD ~SPWI501~
TEXT_SPRINT WIZARD_CLOUDKILL ~SPWI502~
TEXT_SPRINT WIZARD_CONE_OF_COLD ~SPWI503~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_3 ~SPWI504~
TEXT_SPRINT WIZARD_SHADOW_DOOR ~SPWI505~
TEXT_SPRINT WIZARD_DOMINATION ~SPWI506~
TEXT_SPRINT WIZARD_HOLD_MONSTER ~SPWI507~
TEXT_SPRINT WIZARD_CHAOS ~SPWI508~
TEXT_SPRINT WIZARD_FEEBLEMIND ~SPWI509~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY ~SPWI510~
TEXT_SPRINT WIZARD_PROTECTION_FROM_NORMAL_WEAPONS ~SPWI511~
TEXT_SPRINT WIZARD_PROTECTION_FROM_ELECTRICITY ~SPWI512~
TEXT_SPRINT WIZARD_BREACH ~SPWI513~
TEXT_SPRINT WIZARD_LOWER_RESISTANCE ~SPWI514~
TEXT_SPRINT WIZARD_ORACLE ~SPWI515~
TEXT_SPRINT WIZARD_CONJURE_LESSER_FIRE_ELEMENTAL ~SPWI516~
TEXT_SPRINT WIZARD_PROTECTION_FROM_ACID ~SPWI517~
TEXT_SPRINT WIZARD_PHANTOM_BLADE ~SPWI518~
TEXT_SPRINT WIZARD_SPELL_SHIELD ~SPWI519~
TEXT_SPRINT WIZARD_CONJURE_LESSER_AIR_ELEMENTAL ~SPWI520~
TEXT_SPRINT WIZARD_CONJURE_LESSER_EARTH_ELEMENTAL ~SPWI521~
TEXT_SPRINT WIZARD_MINOR_SPELL_TURNING ~SPWI522~
TEXT_SPRINT WIZARD_SUN_FIRE ~SPWI523~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_ABJURATION ~SPWI590~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_CONJURATION ~SPWI591~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_DIVINATION ~SPWI592~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_ENCHANTMENT ~SPWI593~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_ILLUSIONIST ~SPWI594~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_INVOCATION ~SPWI595~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_NECROMANCY ~SPWI596~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_ALTERATION ~SPWI597~

// Level 6

TEXT_SPRINT WIZARD_INVISIBLE_STALKER ~SPWI601~
TEXT_SPRINT WIZARD_GLOBE_OF_INVULNERABILITY ~SPWI602~
TEXT_SPRINT WIZARD_TENSERS_TRANSFORMATION ~SPWI603~
TEXT_SPRINT WIZARD_FLESH_TO_STONE ~SPWI604~
TEXT_SPRINT WIZARD_DEATH_SPELL ~SPWI605~
TEXT_SPRINT WIZARD_PROTECTION_FROM_MAGIC_ENERGY ~SPWI606~
TEXT_SPRINT WIZARD_MISLEAD ~SPWI607~
TEXT_SPRINT WIZARD_PIERCE_MAGIC ~SPWI608~
TEXT_SPRINT WIZARD_TRUE_SIGHT ~SPWI609~
TEXT_SPRINT WIZARD_PROTECTION_FROM_MAGIC_WEAPONS ~SPWI611~
TEXT_SPRINT WIZARD_POWER_WORD_SILENCE ~SPWI612~
TEXT_SPRINT WIZARD_IMPROVED_HASTE ~SPWI613~
TEXT_SPRINT WIZARD_DEATH_FOG ~SPWI614~
TEXT_SPRINT WIZARD_CHAIN_LIGHTNING ~SPWI615~
TEXT_SPRINT WIZARD_DISINTEGRATE ~SPWI616~
TEXT_SPRINT WIZARD_CONTINGENCY ~SPWI617~
TEXT_SPRINT WIZARD_SPELL_DEFLECTION ~SPWI618~
TEXT_SPRINT WIZARD_WYVERN_CALL ~SPWI619~
TEXT_SPRINT WIZARD_CONJURE_FIRE_ELEMENTAL ~SPWI620~
TEXT_SPRINT WIZARD_CONJURE_AIR_ELEMENTAL ~SPWI621~
TEXT_SPRINT WIZARD_CONJURE_EARTH_ELEMENTAL ~SPWI622~
TEXT_SPRINT WIZARD_CARRION ~SPWI623~
TEXT_SPRINT WIZARD_SUMMON_NISHRUU ~SPWI624~
TEXT_SPRINT WIZARD_STONE_TO_FLESH ~SPWI625~

// Level 7

TEXT_SPRINT WIZARD_SPELL_TURNING ~SPWI701~
TEXT_SPRINT WIZARD_PROTECTION_FROM_THE_ELEMENTS ~SPWI702~
TEXT_SPRINT WIZARD_PROJECT_IMAGE ~SPWI703~
TEXT_SPRINT WIZARD_RUBY_RAY_OF_REVERSAL ~SPWI704~
TEXT_SPRINT WIZARD_WARDING_WHIP ~SPWI705~
TEXT_SPRINT WIZARD_CACOFIEND ~SPWI707~
TEXT_SPRINT WIZARD_MANTLE ~SPWI708~
TEXT_SPRINT WIZARD_SPELL_SEQUENCER ~SPWI710~
TEXT_SPRINT WIZARD_SPHERE_OF_CHAOS ~SPWI711~
TEXT_SPRINT WIZARD_DELAYED_BLAST_FIREBALL ~SPWI712~
TEXT_SPRINT WIZARD_FINGER_OF_DEATH ~SPWI713~
TEXT_SPRINT WIZARD_PRISMATIC_SPRAY ~SPWI714~
TEXT_SPRINT WIZARD_POWER_WORD_STUN ~SPWI715~
TEXT_SPRINT WIZARD_MORDENKAINENS_SWORD ~SPWI716~
TEXT_SPRINT WIZARD_SUMMON_EFREET ~SPWI717~
TEXT_SPRINT WIZARD_SUMMON_DJINNI ~SPWI718~
TEXT_SPRINT WIZARD_SUMMON_HAKEASHAR ~SPWI719~
TEXT_SPRINT WIZARD_CONTROL_UNDEAD ~SPWI720~
TEXT_SPRINT WIZARD_MASS_INVISIBILITY ~SPWI721~
TEXT_SPRINT WIZARD_LIMITED_WISH ~SPWI722~
TEXT_SPRINT WIZARD_IMPROVED_CHAOS_SHIELD ~SPWI723~

// Level 8

TEXT_SPRINT WIZARD_PROTECTION_FROM_ENERGY ~SPWI803~
TEXT_SPRINT WIZARD_SIMULACRUM ~SPWI804~
TEXT_SPRINT WIZARD_PIERCE_SHIELD ~SPWI805~
TEXT_SPRINT WIZARD_SUMMON_FIEND ~SPWI807~
TEXT_SPRINT WIZARD_IMPROVED_MANTLE ~SPWI808~
TEXT_SPRINT WIZARD_SPELL_TRIGGER ~SPWI809~
TEXT_SPRINT WIZARD_INCENDIARY_CLOUD ~SPWI810~
TEXT_SPRINT WIZARD_SYMBOL_FEAR ~SPWI811~
TEXT_SPRINT WIZARD_ABI_DALZIMS_HORRID_WILTING ~SPWI812~
TEXT_SPRINT WIZARD_MAZE ~SPWI813~
TEXT_SPRINT WIZARD_POWER_WORD_BLIND ~SPWI815~
TEXT_SPRINT WIZARD_SYMBOL_STUN ~SPWI816~
TEXT_SPRINT WIZARD_SYMBOL_DEATH ~SPWI817~
TEXT_SPRINT WIZARD_BIGBYS_CLENCHED_FIST ~SPWI818~
TEXT_SPRINT FORCE_DAMAGE_1 ~SPWI888~
TEXT_SPRINT WIZARD_NPC_SYMBOL_DEATH ~SPWI897~
TEXT_SPRINT WIZARD_NPC_SYMBOL_STUN ~SPWI898~
TEXT_SPRINT WIZARD_NPC_SYMBOL_FEAR ~SPWI899~

// Level 9

TEXT_SPRINT WIZARD_SPELL_TRAP ~SPWI902~
TEXT_SPRINT WIZARD_SPELL_STRIKE ~SPWI903~
TEXT_SPRINT WIZARD_GATE ~SPWI905~
TEXT_SPRINT WIZARD_ABSOLUTE_IMMUNITY ~SPWI907~
TEXT_SPRINT WIZARD_CHAIN_CONTINGENCY ~SPWI908~
TEXT_SPRINT WIZARD_TIME_STOP ~SPWI909~
TEXT_SPRINT WIZARD_IMPRISONMENT ~SPWI910~
TEXT_SPRINT WIZARD_METEOR_SWARM ~SPWI911~
TEXT_SPRINT WIZARD_POWER_WORD_KILL ~SPWI912~
TEXT_SPRINT WIZARD_WAIL_OF_THE_BANSHEE ~SPWI913~
TEXT_SPRINT WIZARD_ENERGY_DRAIN ~SPWI914~
TEXT_SPRINT WIZARD_BLACK_BLADE_OF_DISASTER ~SPWI915~
TEXT_SPRINT WIZARD_SHAPECHANGE ~SPWI916~
TEXT_SPRINT WIZARD_FREEDOM ~SPWI917~
TEXT_SPRINT WIZARD_BIGBYS_CRUSHING_HAND ~SPWI918~
TEXT_SPRINT WIZARD_WISH ~SPWI919~
TEXT_SPRINT WIZARD_ENERGY_BLADES ~SPWI920~
TEXT_SPRINT WIZARD_IMPROVED_ALUCRITY ~SPWI921~
TEXT_SPRINT WIZARD_DRAGONS_BREATH ~SPWI922~
TEXT_SPRINT WIZARD_SUMMON_PLANATAR_GOOD ~SPWI923~
TEXT_SPRINT WIZARD_SUMMON_PLANATAR_EVIL ~SPWI924~
TEXT_SPRINT WIZARD_COMET ~SPWI925~

// Misc

TEXT_SPRINT QUICK_TELEPORT ~SPWI926~
TEXT_SPRINT SUCCUBUS_ETHEREAL ~SPWI927~
TEXT_SPRINT SUCCUBUS_ENERGY_DRAIN ~SPWI928~
TEXT_SPRINT SUCCUBUS_CHARM_FEMALE ~SPWI929~
TEXT_SPRINT SUCCUBUS_CHARM_MALE ~SPWI930~
TEXT_SPRINT SUCCUBUS_TELEPORT ~SPWI931~
TEXT_SPRINT TANARI_CHANGE ~SPWI932~
TEXT_SPRINT DURLAG_SWORD ~SPWI933~
TEXT_SPRINT CRUSHING_TRAP ~SPWI934~
TEXT_SPRINT SUMMON_SKELETON_WARRIOR3 ~SPWI935~
TEXT_SPRINT SUMMON_SKELETON_WARRIOR2 ~SPWI936~
TEXT_SPRINT SUMMON_SKELETON_WARRIOR ~SPWI937~
TEXT_SPRINT CHARM_HERO ~SPWI939~
TEXT_SPRINT FIREDRAKE_DAMAGE ~SPWI940~
TEXT_SPRINT LOVEM_CHANGE ~SPWI941~
TEXT_SPRINT QUEEN_CHANGE ~SPWI942~
TEXT_SPRINT SIRINE_DIRE_CHARM ~SPWI943~
TEXT_SPRINT DAESEWOLF_CHANGE ~SPWI944~
TEXT_SPRINT LOUPGAR_CHANGE ~SPWI945~
TEXT_SPRINT PLAYER_WEREWOLF_CHANGE ~SPWI946~
TEXT_SPRINT GREATER_WOLFWERE_CHANGE ~SPWI947~
TEXT_SPRINT WEREWOLF_CHANGE ~SPWI948~
TEXT_SPRINT WOLFWERE_CHANGE ~SPWI949~
TEXT_SPRINT FAST_SKULLTRAP ~SPWI950~
TEXT_SPRINT JELLY_SPLIT ~SPWI951~
TEXT_SPRINT DRADEEL_FLAMEBLADE ~SPWI952~
TEXT_SPRINT DRADEEL_BLUE_FIREBALL ~SPWI953~
TEXT_SPRINT DRADEEL_MINOR_GLOBE ~SPWI954~
TEXT_SPRINT PAIN ~SPWI955~
TEXT_SPRINT FEAR ~SPWI956~
TEXT_SPRINT RED_FIREBALL ~SPWI957~
TEXT_SPRINT POWERWORD_BLIND ~SPWI958~
TEXT_SPRINT POWERWORD_STUN ~SPWI959~
TEXT_SPRINT POWERWORD_KILL ~SPWI960~
TEXT_SPRINT DOPPLEGANGER_CHANGE4 ~SPWI961~
TEXT_SPRINT DOPPLEGANGER_CHANGE5 ~SPWI962~
TEXT_SPRINT DOPPLEGANGER_CHANGE6 ~SPWI963~
TEXT_SPRINT DOPPLEGANGER_CHANGE7 ~SPWI964~
TEXT_SPRINT DOPPLEGANGER_CHANGE8 ~SPWI965~
TEXT_SPRINT SAREVOK_STRIKE ~SPWI979~
TEXT_SPRINT FIREBALL_DEATH ~SPWI980~
TEXT_SPRINT MUSHROOM_FIRE ~SPWI981~
TEXT_SPRINT DAERRAGH ~SPWI982~
TEXT_SPRINT RISE_FROM_ASH ~SPWI983~
TEXT_SPRINT RED_SWIRL ~SPWI984~
TEXT_SPRINT RED_HOLY_MIGHT ~SPWI985~
TEXT_SPRINT SPIDER_SUMMON ~SPWI986~
TEXT_SPRINT DOPPLEGANGER_CHANGE_DEFAULT_LESSER ~SPWI987~
TEXT_SPRINT DOPPLEGANGER_CHANGE_DEFAULT ~SPWI988~
TEXT_SPRINT EFFECT_ONLY ~SPWI989~
TEXT_SPRINT DOPPLEGANGER_CHANGE3 ~SPWI990~
TEXT_SPRINT DOPPLEGANGER_RASHAD ~SPWI991~
TEXT_SPRINT DOPPLEGANGER_CHANGE2 ~SPWI992~
TEXT_SPRINT DOPPLEGANGER_CHANGE ~SPWI993~
TEXT_SPRINT PHASE_SPIDER_TELEPORT ~SPWI994~
TEXT_SPRINT DRYAD_TELEPORT ~SPWI995~
TEXT_SPRINT CHARM_KORAX ~SPWI996~
TEXT_SPRINT GORION_LIGHTNING ~SPWI997~
TEXT_SPRINT GORION_MAGIC_MISSILE ~SPWI998~
TEXT_SPRINT DIETY_KILL ~SPWI999~

// Innate abilities

// Bhaalpowers

TEXT_SPRINT INNATE_CURE_LIGHT_WOUNDS ~SPIN101~
TEXT_SPRINT INNATE_SLOW_POISON ~SPIN102~
TEXT_SPRINT INNATE_DRAW_UPON_HOLY_MIGHT ~SPIN103~
TEXT_SPRINT INNATE_LARLOCHS_MINOR_DRAIN ~SPIN104~
TEXT_SPRINT INNATE_HORROR ~SPIN105~
TEXT_SPRINT INNATE_VAMPIRIC_TOUCH ~SPIN106~

// Misc

TEXT_SPRINT MINSC_BERSERK ~SPIN117~
TEXT_SPRINT AVENGER_SHAPESHIFT_NATURAL_FORM ~SPIN122~
TEXT_SPRINT DRUID_SHAPESHIFT_FROM_BLACKBEAR ~SPIN123~
TEXT_SPRINT SHAPESHIFTER_SHAPESHIFT_NATURAL_FORM ~SPIN124~
TEXT_SPRINT SHAPESHIFT_NATURAL_FORM_1 ~SPIN150~
TEXT_SPRINT SHAPESHIFT_NATURAL_FORM_2 ~SPIN151~
TEXT_SPRINT SHAPECHANGE_MIND_FLAYER ~SPIN152~
TEXT_SPRINT SHAPECHANGE_IRON_GOLEM ~SPIN153~
TEXT_SPRINT SHAPECHANGE_GIANT_TROLL ~SPIN154~
TEXT_SPRINT SHAPECHANGE_GREATER_WOLFWERE ~SPIN155~
TEXT_SPRINT SHAPECHANGE_FIRE_ELEMENTAL ~SPIN156~
TEXT_SPRINT SHAPECHANGE_EARTH_ELEMENTAL ~SPIN157~
TEXT_SPRINT SALAMANDER_BREATHE_FIREBALL ~SPIN160~
TEXT_SPRINT ABAZIGAL_SHOCKWAVE ~SPIN531~
TEXT_SPRINT DRAGON_LOWER_ELECTRICAL ~SPIN532~
TEXT_SPRINT SENDAI_CHANGE ~SPIN533~
TEXT_SPRINT SUMMON_DEVIL_SHADE ~SPIN534~
TEXT_SPRINT GREEN_DRAGON_BREATH ~SPIN535~
TEXT_SPRINT LICH_FEAR ~SPIN536~
TEXT_SPRINT TROLL_FIRE_CHANGE ~SPIN537~
TEXT_SPRINT MAJOR_POLYMORPH ~SPIN538~
TEXT_SPRINT FLAMING_SKULL_BOLT ~SPIN539~
TEXT_SPRINT RABBIT_POWER ~SPIN540~
TEXT_SPRINT SAR_DIVINATION ~SPIN541~
TEXT_SPRINT PSIONIC_DISINTEGRATE ~SPIN542~
TEXT_SPRINT PSIONIC_INFLICT_PAIN ~SPIN543~
TEXT_SPRINT PSIONIC_SUPERIOR_INVISIBILITY ~SPIN544~
TEXT_SPRINT PSIONIC_LIFE_DRAIN ~SPIN545~
TEXT_SPRINT PSIONIC_INERTIAL_BARRIER ~SPIN546~
TEXT_SPRINT PSIONIC_PROJECT_FORCE ~SPIN547~
TEXT_SPRINT DEMOGORGON_GATE ~SPIN548~
TEXT_SPRINT SUMMON_INFERNAL_HOST ~SPIN549~
TEXT_SPRINT HIVE_MOTHER_ANTIMAGIC_RAY ~SPIN550~
TEXT_SPRINT HIVE_MOTHER_CAUSE_SERIOUS_WOUNDS ~SPIN551~
TEXT_SPRINT HIVE_MOTHER_DISINTEGRATE ~SPIN552~
TEXT_SPRINT NALMISSRA_CHARM ~SPIN553~
TEXT_SPRINT GAIN_ONE_CHA_PERMANENT ~SPIN554~
TEXT_SPRINT GAIN_ONE_WIS_PERMANENT ~SPIN555~
TEXT_SPRINT GAIN_ONE_INT_PERMANENT ~SPIN556~
TEXT_SPRINT GAIN_ONE_DEX_PERMANENT ~SPIN557~
TEXT_SPRINT ERINYES_CHARM ~SPIN558~
TEXT_SPRINT BURNING_MAN_KEENING ~SPIN559~
TEXT_SPRINT BURNING_MAN_CINDER_SHOWER ~SPIN560~
TEXT_SPRINT FIRE_GIANT_LAVA ~SPIN561~
TEXT_SPRINT ICE_GOLEM_STEAM ~SPIN562~
TEXT_SPRINT HOLY_PILLAR_VISUAL ~SPIN563~
TEXT_SPRINT SKULL_EXPLODE ~SPIN564~
TEXT_SPRINT GAROCK_TELEPORT ~SPIN565~
TEXT_SPRINT MIMIC_WEB ~SPIN566~
TEXT_SPRINT MIMIC_FIRE ~SPIN567~
TEXT_SPRINT MIMIC_POISON ~SPIN568~
TEXT_SPRINT SUMMON_ICE_SALAMANDER ~SPIN569~
TEXT_SPRINT SUMMON_FIRE_ELEMENTAL ~SPIN570~
TEXT_SPRINT SUCCUBUS_KISS ~SPIN571~
TEXT_SPRINT CUTSCENE_HASTE ~SPIN572~
TEXT_SPRINT IMOEN_BHAAL2 ~SPIN573~
TEXT_SPRINT IMOEN_BHAAL1 ~SPIN574~
TEXT_SPRINT VORTEX_WEB ~SPIN575~
TEXT_SPRINT DENSE_PUDDING_SPLIT ~SPIN576~
TEXT_SPRINT GAIN_ONE_THACO ~SPIN577~
TEXT_SPRINT GAIN_ONE_AC ~SPIN578~
TEXT_SPRINT POWER_AMP ~SPIN579~
TEXT_SPRINT IMPRISONMENT_NO_SAVE ~SPIN580~
TEXT_SPRINT RESTORATION_IGNORE_RESIST ~SPIN581~
TEXT_SPRINT CONFUSION_NO_SAVE ~SPIN582~
TEXT_SPRINT POISON_NO_SAVE ~SPIN583~
TEXT_SPRINT GAIN_HASTE_TEMPORARY ~SPIN584~
TEXT_SPRINT GAIN_MAGIC_RESIST_PERMANENT ~SPIN585~
TEXT_SPRINT LOSE_FIFTEEN_LEVELS ~SPIN586~
TEXT_SPRINT LOSE_FIVE_LEVELS ~SPIN587~
TEXT_SPRINT LOSE_ONE_DEX_PERMANENT ~SPIN588~
TEXT_SPRINT LOSE_ONE_INT_PERMANENT ~SPIN589~
TEXT_SPRINT GAIN_ONE_CON_PERMANENT ~SPIN590~
TEXT_SPRINT GAIN_ONE_STR_PERMANENT ~SPIN591~
TEXT_SPRINT HELM_RITUAL_SCROLL ~SPIN592~
TEXT_SPRINT ODREN_RITUAL_SCROLL ~SPIN593~
TEXT_SPRINT DEMOGORGON_CHANGE ~SPIN594~
TEXT_SPRINT YELLOW_DRAGON_BREATH ~SPIN595~
TEXT_SPRINT BROWN_DRAGON_BREATH ~SPIN596~
TEXT_SPRINT BLUE_DRAGON_BREATH ~SPIN597~
TEXT_SPRINT SAREVOK_FLASHY1 ~SPIN598~
TEXT_SPRINT FIRE_HEALING ~SPIN599~
TEXT_SPRINT SAREVOK_SOULSTEAL ~SPIN600~
TEXT_SPRINT SPECIAL_SWEET_AIR ~SPIN601~
TEXT_SPRINT CHROMATIC_DEMON_RED ~SPIN602~
TEXT_SPRINT CHROMATIC_DEMON_WHITE ~SPIN603~
TEXT_SPRINT CHROMATIC_DEMON_GREEN ~SPIN604~
TEXT_SPRINT CHROMATIC_DEMON_YELLOW ~SPIN605~

// Deck of Many Things

TEXT_SPRINT DECK_SUN ~SPIN606~
TEXT_SPRINT DECK_JESTER ~SPIN607~
TEXT_SPRINT DECK_VIZIER ~SPIN608~
TEXT_SPRINT DECK_GEM ~SPIN609~
TEXT_SPRINT DECK_FATES ~SPIN610~
TEXT_SPRINT DECK_COMET ~SPIN611~
TEXT_SPRINT DECK_FOOL ~SPIN612~
TEXT_SPRINT DECK_TALONS ~SPIN613~
TEXT_SPRINT DECK_ROGUE ~SPIN614~
TEXT_SPRINT DECK_KNIGHT ~SPIN615~
TEXT_SPRINT DECK_FLAMES ~SPIN616~
TEXT_SPRINT DECK_EURYALE ~SPIN617~
TEXT_SPRINT DECK_MOON ~SPIN618~
TEXT_SPRINT DECK_THRONE ~SPIN619~
TEXT_SPRINT DECK_KEY ~SPIN621~
TEXT_SPRINT DECK_SKULL ~SPIN622~
TEXT_SPRINT DECK_MAGICIAN ~SPIN623~
TEXT_SPRINT DECK_VOID ~SPIN624~
TEXT_SPRINT DECK_RUIN ~SPIN625~
TEXT_SPRINT DECK_DONJON ~SPIN626~
TEXT_SPRINT FROZEN_DEATH ~SPIN627~
TEXT_SPRINT SLOW_FREEZE ~SPIN628~
TEXT_SPRINT DECK_WHEEL ~SPIN629~
TEXT_SPRINT DECK_STRENGTH ~SPIN630~
TEXT_SPRINT DECK_CONSTRUCT ~SPIN631~
TEXT_SPRINT DECK_EMPEROR ~SPIN632~
TEXT_SPRINT DECK_EMPRESS ~SPIN633~
TEXT_SPRINT DECK_HIGH_PRIESTESS ~SPIN634~
TEXT_SPRINT DECK_STRIFE ~SPIN635~
TEXT_SPRINT DECK_DEFIANCE ~SPIN636~
TEXT_SPRINT DECK_GUILE ~SPIN637~
TEXT_SPRINT DECK_TRIUMPH ~SPIN638~
TEXT_SPRINT DECK_PLAGUE ~SPIN639~
TEXT_SPRINT DECK_XP_DRAIN ~SPIN640~
TEXT_SPRINT DECK_VITALITY_DRAIN ~SPIN641~

// Misc

TEXT_SPRINT POISONOUS_CLOUD ~SPIN642~
TEXT_SPRINT FAN_BLOW ~SPIN643~
TEXT_SPRINT BALOR_FIRE_SHIELD ~SPIN644~
TEXT_SPRINT WILD_MAGIC_AREA ~SPIN645~
TEXT_SPRINT DEAD_MAGIC_AREA ~SPIN646~
TEXT_SPRINT DISPEL_NO_SAVE ~SPIN647~
TEXT_SPRINT HOLD_PERSON_NO_SAVE ~SPIN648~
TEXT_SPRINT ENTER_POCKET_PLANE ~SPIN649~
TEXT_SPRINT DM_SHIELD ~SPIN650~
TEXT_SPRINT DM_SEE_INVISIBLE ~SPIN651~
TEXT_SPRINT DM_MAGIC_PROTECTION ~SPIN652~
TEXT_SPRINT DM_COLD_PROTECTION ~SPIN653~
TEXT_SPRINT DM_FIRE_PROTECTION ~SPIN654~
TEXT_SPRINT DM_IMPROVED_HASTE ~SPIN655~
TEXT_SPRINT VIEKANG_LIGHTNING ~SPIN656~
TEXT_SPRINT DO_SOME_EFFECTS ~SPIN657~
TEXT_SPRINT HELL_BUFFET ~SPIN658~
TEXT_SPRINT TROLL_CHANGE_NITHIRI ~SPIN659~
TEXT_SPRINT POOF_GONE ~SPIN660~
TEXT_SPRINT EDWINA_IN_HELL ~SPIN661~
TEXT_SPRINT EDWIN_CHANGE_BACK ~SPIN662~
TEXT_SPRINT CREATE_YOSHIMO_BLADE ~SPIN663~
TEXT_SPRINT NETHER_SCROLL ~SPIN664~
TEXT_SPRINT BEHOLDER_BLAST_VISUAL2 ~SPIN665~
TEXT_SPRINT ZOMBIE_LEVEL_DRAIN ~SPIN666~
TEXT_SPRINT SLAYER_BACK_TO_HUMAN_NOVIS ~SPIN667~
TEXT_SPRINT REMOVE_NON_PERMANENT_DEATH ~SPIN668~
TEXT_SPRINT APPLY_NON_PERMANENT_DEATH ~SPIN669~
TEXT_SPRINT SEA_TROLL_CHANGE ~SPIN670~
TEXT_SPRINT SWOOSH_GONE ~SPIN671~
TEXT_SPRINT QUICK_INVISIBLE ~SPIN672~
TEXT_SPRINT SPORE_DEATH ~SPIN673~
TEXT_SPRINT MIST_CHAOS ~SPIN674~
TEXT_SPRINT MIST_HORROR ~SPIN675~
TEXT_SPRINT INVOKE_COURAGE ~SPIN676~
TEXT_SPRINT SUMMON_POISON ~SPIN677~
TEXT_SPRINT ANOMEN_TITLE ~SPIN678~
TEXT_SPRINT HEAL_NO_VISUAL ~SPIN679~
TEXT_SPRINT HARPER_DEATH_SONG ~SPIN680~
TEXT_SPRINT BANSHEE_WAIL ~SPIN681~
TEXT_SPRINT DRAGON_LOWER_FIRE ~SPIN682~
TEXT_SPRINT FIGURINE_SPIDER_WEB ~SPIN683~
TEXT_SPRINT KOA_TRUE_SIGHT_NO_VIS ~SPIN684~
TEXT_SPRINT MAGIC_MISSILE_SURE_HIT ~SPIN685~
TEXT_SPRINT PROTECTION_MAGIC_WEAPON_NOEFF ~SPIN686~
TEXT_SPRINT SHADOW_DRAGON_SHADOWS ~SPIN687~
TEXT_SPRINT BLACK_DRAGON_PLANT ~SPIN688~
TEXT_SPRINT BLACK_DRAGON_INSECT ~SPIN689~
TEXT_SPRINT HOLY_LIGHT_FROM_ABOVE ~SPIN690~
TEXT_SPRINT BLACK_DRAGON_BREATH ~SPIN691~
TEXT_SPRINT DRAGON_SILENCE ~SPIN692~
TEXT_SPRINT RED_DRAGON_HIT ~SPIN693~
TEXT_SPRINT DRAGON_STONE_SKIN ~SPIN694~
TEXT_SPRINT DRAGON_WING_BUFFET ~SPIN695~
TEXT_SPRINT MOON_DOG_HOWL ~SPIN696~
TEXT_SPRINT HASTE_SELF ~SPIN697~
TEXT_SPRINT NON_DETECTION_SELF ~SPIN698~
TEXT_SPRINT INVISIBILITY_SELF ~SPIN699~
TEXT_SPRINT TROLL_SETHP1 ~SPIN700~
TEXT_SPRINT DEATHKNIGHT_FIREBALL ~SPIN701~
TEXT_SPRINT FAKE_FLAME_STRIKE ~SPIN702~
TEXT_SPRINT AERIE_DISPEL_MAGIC ~SPIN703~
TEXT_SPRINT NYMPH_CONFUSION ~SPIN704~
TEXT_SPRINT TRAP_VENT ~SPIN706~
TEXT_SPRINT TRAP_DARTS ~SPIN707~
TEXT_SPRINT TRAP_SLIME ~SPIN708~
TEXT_SPRINT TRAP_SPEAR ~SPIN709~
TEXT_SPRINT SPELL_DEFLECTION_NO_VISUAL ~SPIN710~
TEXT_SPRINT FINAL_HEAL ~SPIN711~
TEXT_SPRINT MULTIPLAYER_ANTIMAGIC ~SPIN712~
TEXT_SPRINT ICE_DUST ~SPIN713~
TEXT_SPRINT CELESTIAL_BOLT ~SPIN714~
TEXT_SPRINT TROLL_RAT_SPAWN ~SPIN715~
TEXT_SPRINT SLAYER_IMMUNE_TO_DAMAGE ~SPIN716~
TEXT_SPRINT SLAYER_CHANGE_CUT_SCENE ~SPIN717~
TEXT_SPRINT SLAYER_BACK_TO_HUMAN ~SPIN718~
TEXT_SPRINT CUTSCENE_METEOR_SWARM ~SPIN719~
TEXT_SPRINT CUTSCENE_DAMAGE_1C ~SPIN720~
TEXT_SPRINT CUTSCENE_DAMAGE_1B ~SPIN721~
TEXT_SPRINT GREAT_DRUID_TITLE ~SPIN722~
TEXT_SPRINT DRAGON_RAIN ~SPIN723~
TEXT_SPRINT RAISSA_RESTORE ~SPIN724~
TEXT_SPRINT SKIN_DANCER_RESTORE_2 ~SPIN725~
TEXT_SPRINT CUTSCENE_DAMAGE_1 ~SPIN726~
TEXT_SPRINT NOSAVE_PSIONIC_BLAST ~SPIN727~
TEXT_SPRINT SKIN_DANCER_RESTORE ~SPIN728~
TEXT_SPRINT SKIN_DANCER_SWITCH ~SPIN729~
TEXT_SPRINT SUMMON_FUNGUS ~SPIN730~
TEXT_SPRINT WISH_SPELL_FAILURE ~SPIN731~
TEXT_SPRINT WISH_LOSE_SPELL ~SPIN732~
TEXT_SPRINT WISH_POISON ~SPIN733~
TEXT_SPRINT WISH_HEAL_PARTY ~SPIN734~
TEXT_SPRINT WISH_RABBIT ~SPIN735~
TEXT_SPRINT WISH_GLOBE ~SPIN736~
TEXT_SPRINT WISH_MEMORIZE ~SPIN737~
TEXT_SPRINT WISH_PLANE ~SPIN738~
TEXT_SPRINT TROLL_SPECTRAL_CHANGE ~SPIN739~
TEXT_SPRINT TROLL_SNOW_CHANGE ~SPIN740~
TEXT_SPRINT TROLL_SPIRIT_CHANGE ~SPIN741~
TEXT_SPRINT TROLL_GIANT_CHANGE ~SPIN742~
TEXT_SPRINT TROLL_FRESHWATER_CHANGE ~SPIN743~
TEXT_SPRINT TROLL_DESERT_CHANGE ~SPIN744~
TEXT_SPRINT AERIE_PORTRAIT ~SPIN745~
TEXT_SPRINT RESTORE_FULL_HEALTH ~SPIN746~
TEXT_SPRINT HELL_SELFISH_EVIL ~SPIN747~
TEXT_SPRINT HELL_SELFISH_GOOD ~SPIN748~
TEXT_SPRINT HELL_WRATH_EVIL ~SPIN749~
TEXT_SPRINT HELL_WRATH_GOOD ~SPIN750~
TEXT_SPRINT HELL_PRIDE_EVIL ~SPIN751~
TEXT_SPRINT HELL_PRIDE_GOOD ~SPIN752~
TEXT_SPRINT HELL_FEAR_EVIL ~SPIN753~
TEXT_SPRINT HELL_FEAR_GOOD ~SPIN754~
TEXT_SPRINT HELL_GREED_EVIL ~SPIN755~
TEXT_SPRINT HELL_GREED_GOOD ~SPIN756~
TEXT_SPRINT IRENICUS_WORD_OF_POWER ~SPIN757~
TEXT_SPRINT PLAYER1_WORD_OF_POWER ~SPIN758~
TEXT_SPRINT HELL_GAIN_CHR ~SPIN759~
TEXT_SPRINT HELL_GAIN_CON ~SPIN760~
TEXT_SPRINT HELL_GAIN_DEX ~SPIN761~
TEXT_SPRINT HELL_GAIN_WIS ~SPIN762~
TEXT_SPRINT HELL_GAIN_INT ~SPIN763~
TEXT_SPRINT HELL_GAIN_STR ~SPIN764~
TEXT_SPRINT HELL_LOSE_XP ~SPIN765~
TEXT_SPRINT HELL_LOSE_DEX ~SPIN766~
TEXT_SPRINT HELL_LOSE_HP ~SPIN767~
TEXT_SPRINT HELL_DISPELL ~SPIN768~
TEXT_SPRINT HELL_HOLD ~SPIN769~
TEXT_SPRINT HELL_EXPLODE ~SPIN770~
TEXT_SPRINT HELL_DAMAGE_HALF ~SPIN771~
TEXT_SPRINT HELL_FEAR ~SPIN772~
TEXT_SPRINT EVIL_LAYONHANDS ~SPIN773~
TEXT_SPRINT PSIONIC_MAZE ~SPIN774~
TEXT_SPRINT PSIONIC_MIND_BLAST ~SPIN775~
TEXT_SPRINT MAKE_STATUE ~SPIN776~
TEXT_SPRINT BEHOLDER_BLAST_VISUAL ~SPIN777~
TEXT_SPRINT WILD_MAGIC_ZONE ~SPIN778~
TEXT_SPRINT ANTI_MAGIC_ZONE ~SPIN779~
TEXT_SPRINT FLASHY_DEATH_3 ~SPIN780~
TEXT_SPRINT FLASHY_DEATH_2 ~SPIN781~
TEXT_SPRINT FLASHY_DEATH_1 ~SPIN782~
TEXT_SPRINT SLAYER_ENEMY ~SPIN783~
TEXT_SPRINT SNAKE_GAZE ~SPIN784~
TEXT_SPRINT PERM_CHARM ~SPIN785~
TEXT_SPRINT LICH_IMPRISON ~SPIN786~
TEXT_SPRINT SMALL_DAMAGE_SPELL ~SPIN787~
TEXT_SPRINT DEMILICH_TRAP_SOUL ~SPIN788~
TEXT_SPRINT DEMILICH_DEATH ~SPIN789~
TEXT_SPRINT LONG_VISUAL2 ~SPIN790~
TEXT_SPRINT TROLL_ICE_CHANGE ~SPIN791~
TEXT_SPRINT LONG_VISUAL ~SPIN792~
TEXT_SPRINT FLASHY_DEATH_YEAH ~SPIN793~
TEXT_SPRINT FLASHY_4 ~SPIN794~
TEXT_SPRINT FLASHY_3 ~SPIN795~
TEXT_SPRINT FLASHY_2 ~SPIN796~
TEXT_SPRINT FLASHY_1 ~SPIN797~
TEXT_SPRINT BODHI_BAT_ASYLUM ~SPIN798~
TEXT_SPRINT DACE_FLAME ~SPIN799~
TEXT_SPRINT FLAME_HEAD ~SPIN800~
TEXT_SPRINT NO_FEAR_PARTY ~SPIN801~
TEXT_SPRINT MIND_CRIPPLE ~SPIN802~
TEXT_SPRINT DACE_MIST_FORM_CHANGE ~SPIN803~
TEXT_SPRINT PSIONIC_EMOTION_KILL ~SPIN804~
TEXT_SPRINT THIEF_DETECT_ILLUSION ~SPIN805~
TEXT_SPRINT LICH_REPLACE_SELF ~SPIN806~
TEXT_SPRINT SLAYER_FEAR ~SPIN807~
TEXT_SPRINT DRAIN_PARTY ~SPIN808~
TEXT_SPRINT BODHI_MIST_FORM_CHANGE ~SPIN809~
TEXT_SPRINT GIVE_SLAYER_POWER ~SPIN810~
TEXT_SPRINT VAMPIRE_FORM_CHANGE ~SPIN811~
TEXT_SPRINT DEL_VAMP_FORM_CHANGE ~SPIN812~
TEXT_SPRINT SLAVE_CHUNK ~SPIN813~
TEXT_SPRINT TANOVA_MIST_FORM_CHANGE ~SPIN814~
TEXT_SPRINT DEL_MIST_FORM_CHANGE ~SPIN815~
TEXT_SPRINT VALEN_MIST_FORM_CHANGE ~SPIN816~
TEXT_SPRINT C6BODHI_WEAKNESS ~SPIN817~
TEXT_SPRINT C6VAMPIRE_WEAKNESS ~SPIN818~
TEXT_SPRINT LAVA_BURST ~SPIN819~
TEXT_SPRINT ELVEN_GUARD_WAIL ~SPIN820~
TEXT_SPRINT LONG_RED_MIGHT ~SPIN821~
TEXT_SPRINT SLAYER_START ~SPIN822~
TEXT_SPRINT SLAYER_CHANGE_TWO ~SPIN823~
TEXT_SPRINT DEATH_CURSE ~SPIN824~
TEXT_SPRINT DROW_CHANGE ~SPIN825~
TEXT_SPRINT MAZZY_STRENGTH ~SPIN826~
TEXT_SPRINT MAZZY_LAY ~SPIN827~
TEXT_SPRINT MAZZY_HASTE ~SPIN828~
TEXT_SPRINT JAN_AMMO ~SPIN829~
TEXT_SPRINT UNDER_NORM ~SPIN830~
TEXT_SPRINT UNDER_SQUIRREL ~SPIN831~
TEXT_SPRINT SILVER_DRAGON_BREATH_PARALIZATION ~SPIN832~
TEXT_SPRINT SILVER_DRAGON_BREATH_COLD ~SPIN833~
TEXT_SPRINT BRAIN_PSIONIC_BLAST ~SPIN834~
TEXT_SPRINT ILLUSION_DEATH ~SPIN835~
TEXT_SPRINT JON_ALL_DEAD ~SPIN836~
TEXT_SPRINT JON_WISH ~SPIN837~
TEXT_SPRINT LOSE_ALL ~SPIN838~
TEXT_SPRINT HULK_CONFUSION ~SPIN839~
TEXT_SPRINT BOOK_GOLEM ~SPIN840~
TEXT_SPRINT BOOK_BEHOLD ~SPIN841~
TEXT_SPRINT BOOK_MIND ~SPIN842~
TEXT_SPRINT BOOK_UMBER ~SPIN843~
TEXT_SPRINT BOOK_SPIDER ~SPIN844~
TEXT_SPRINT BOOK_KOBOLD ~SPIN845~
TEXT_SPRINT SAND_DIE ~SPIN846~
TEXT_SPRINT FIRAMB05_CHANGE ~SPIN847~
TEXT_SPRINT DISARM_ENEMY ~SPIN848~
TEXT_SPRINT TROLL_SMALL_CHANGE ~SPIN849~
TEXT_SPRINT DGTROLL_CHANGE ~SPIN850~
TEXT_SPRINT FIRAMB01_CHANGE ~SPIN851~
TEXT_SPRINT SLAYER_CHANGE ~SPIN852~
TEXT_SPRINT FORCE_SPHERE ~SPIN853~
TEXT_SPRINT MAGNET ~SPIN854~
TEXT_SPRINT SUMMON_DJINN_TRAP ~SPIN855~
TEXT_SPRINT SUMMON_DEATH_KNIGHT ~SPIN856~
TEXT_SPRINT SUMMON_PIT_FIEND ~SPIN857~
TEXT_SPRINT ONE_INT ~SPIN858~
TEXT_SPRINT ONE_WIS ~SPIN859~
TEXT_SPRINT ONE_DEX ~SPIN860~
TEXT_SPRINT ONE_CON ~SPIN861~
TEXT_SPRINT NOHOLD_PARTY ~SPIN862~
TEXT_SPRINT HOLD_PARTY ~SPIN863~
TEXT_SPRINT TRANSFORMATION_DEATH ~SPIN864~
TEXT_SPRINT FORCE_STONE_TRAP ~SPIN865~
TEXT_SPRINT FORCE_DISPEL_MAGIC ~SPIN866~
TEXT_SPRINT RED_PILLAR_VISUAL ~SPIN867~
TEXT_SPRINT CERND_CERND ~SPIN868~
TEXT_SPRINT CERND_BEAR ~SPIN869~
TEXT_SPRINT SUMMON_SHADOW_WOLF ~SPIN870~
TEXT_SPRINT END_EXPLORE ~SPIN871~
TEXT_SPRINT FIVE_ROUND_ENCHANTMENT_IMMUNITY ~SPIN872~
TEXT_SPRINT UNPAUSE_CASTER ~SPIN873~
TEXT_SPRINT FALDORN_PANTHER ~SPIN874~
TEXT_SPRINT ANATH_WEREWOLF2 ~SPIN875~
TEXT_SPRINT ANATH_WEREWOLF ~SPIN876~
TEXT_SPRINT APPRENTI_DEATH ~SPIN877~
TEXT_SPRINT SHADOW_DRAIN ~SPIN878~
TEXT_SPRINT MAKE_SHADOW ~SPIN879~
TEXT_SPRINT SUMMON_SHADOW ~SPIN880~
TEXT_SPRINT GREATER_WEREWOLF_CHANGE ~SPIN881~
TEXT_SPRINT VAMPIRE_FEAR ~SPIN882~
TEXT_SPRINT VAMPIRE_DOMINATION ~SPIN883~
TEXT_SPRINT CHICKEN_CHANGE ~SPIN884~
TEXT_SPRINT KAMIKAZE_EXPLOSION ~SPIN885~
TEXT_SPRINT RAELIS_OPEN_PORTAL ~SPIN886~
TEXT_SPRINT SUMMONED_MIND ~SPIN887~
TEXT_SPRINT SURE_STONE_SHATTER ~SPIN888~
TEXT_SPRINT SURE_STONED ~SPIN889~
TEXT_SPRINT DEMON_FEAR ~SPIN890~
TEXT_SPRINT MOON_DOG_FEAR ~SPIN891~
TEXT_SPRINT SURE_SLEEP ~SPIN892~
TEXT_SPRINT SHADOW_DRAGON_BREATH ~SPIN893~
TEXT_SPRINT RED_DRAGON_BREATH ~SPIN894~
TEXT_SPRINT DRAGON_FEAR ~SPIN895~
TEXT_SPRINT REPULSE_X ~SPIN896~
TEXT_SPRINT BEHOLDER_GAS_SPORE ~SPIN897~
TEXT_SPRINT ARCHER_PROTECTION ~SPIN898~
TEXT_SPRINT ZOMBIE_SICKNESS ~SPIN899~
TEXT_SPRINT ZOMBIE_CHANGE ~SPIN900~
TEXT_SPRINT ZOMBIE_CON_LOSS ~SPIN901~
TEXT_SPRINT BODVAM02_MIST_CHANGE ~SPIN902~
TEXT_SPRINT BODVAM01_MIST_CHANGE ~SPIN903~
TEXT_SPRINT LASSAL_MIST_CHANGE ~SPIN904~
TEXT_SPRINT DO_NOTHING ~SPIN905~
TEXT_SPRINT THREE_ROUND_ENCHANTMENT_IMMUNITY ~SPIN906~
TEXT_SPRINT FIFTY_PERCENT_DAMAGE_ARROW ~SPIN907~
TEXT_SPRINT FIFTY_PERCENT_DAMAGE ~SPIN908~
TEXT_SPRINT PSIONIC_EGOWHIP ~SPIN909~
TEXT_SPRINT PSIONIC_DOMINATION ~SPIN910~
TEXT_SPRINT PSIONIC_BALLISTIC ~SPIN911~
TEXT_SPRINT PSIONIC_DETONATE ~SPIN912~
TEXT_SPRINT MIMIC_ACID ~SPIN913~
TEXT_SPRINT MIMIC_GLUE ~SPIN914~
TEXT_SPRINT SPIDER_CHANGE ~SPIN915~
TEXT_SPRINT EDWIN_CHANGE ~SPIN916~
TEXT_SPRINT MANE_GAS ~SPIN917~
TEXT_SPRINT HARPASS_CHANGE ~SPIN918~
TEXT_SPRINT JAHEIRA_WEAKNESS ~SPIN919~
TEXT_SPRINT BEHOLDER_SPELL_TURNING ~SPIN920~
TEXT_SPRINT REVENANT_CHANGE ~SPIN922~
TEXT_SPRINT GENIE_LIMITED_WISH_HEAL_ALL ~SPIN923~
TEXT_SPRINT COVER_PARTIAL ~SPIN924~
TEXT_SPRINT COVER_FULL ~SPIN925~
TEXT_SPRINT MEPHIT_WATER_JET ~SPIN926~
TEXT_SPRINT MEPHIT_RAINSTORM ~SPIN927~
TEXT_SPRINT MEPHIT_MIST ~SPIN929~
TEXT_SPRINT MEPHIT_LAVA ~SPIN930~
TEXT_SPRINT MEPHIT_SOOTY_BALL ~SPIN931~
TEXT_SPRINT MEPHIT_BOLT ~SPIN932~
TEXT_SPRINT MEPHIT_LIGHTNING_BOLT ~SPIN933~
TEXT_SPRINT MEPHIT_SALT_CRYSTAL ~SPIN934~
TEXT_SPRINT MEPHIT_GLASS_DUST ~SPIN935~
TEXT_SPRINT MEPHIT_ICE_SHARD ~SPIN936~
TEXT_SPRINT MEPHIT_COLOR_SPRAY ~SPIN937~
TEXT_SPRINT MEPHIT_FLAME_FAN ~SPIN938~
TEXT_SPRINT MEPHIT_FLAME_JET ~SPIN939~
TEXT_SPRINT MEPHIT_STINKING_CLOUD ~SPIN940~
TEXT_SPRINT MEPHIT_SPIT_ROCK ~SPIN941~
TEXT_SPRINT MEPHIT_GRIT ~SPIN942~
TEXT_SPRINT MEPHIT_BLUR ~SPIN943~
TEXT_SPRINT CUTSCENE_POWERWORD_STUN ~SPIN944~
TEXT_SPRINT CUTSCENE_SPELLSTRIKE ~SPIN945~
TEXT_SPRINT CUTSCENE_BREACH ~SPIN946~
TEXT_SPRINT CUTSCENE_MIND_FOG ~SPIN947~
TEXT_SPRINT CUTSCENE_LOWER_RESISTANCE ~SPIN948~
TEXT_SPRINT CUTSCENE_RUBY_RAY_OF_REVERSAL ~SPIN949~
TEXT_SPRINT CUTSCENE_FLESH_TO_STONE ~SPIN950~
TEXT_SPRINT CUTSCENE_POWERWORD_KILL ~SPIN951~
TEXT_SPRINT CUTSCENE_PHANTASMAL_KILLER ~SPIN952~
TEXT_SPRINT CUTSCENE_IMPRISONMENT ~SPIN953~
TEXT_SPRINT SIRINE_TELEPORT_FAKE ~SPIN954~
TEXT_SPRINT TROLL_CHANGE ~SPIN955~
TEXT_SPRINT HELL_HOUND_FLAME ~SPIN956~
TEXT_SPRINT GHOULLORD_FEAR ~SPIN957~
TEXT_SPRINT ULITHARID_CURE_SERIOUS_WOUNDS ~SPIN958~
TEXT_SPRINT ULITHARID_PSIONIC_BLAST ~SPIN959~
TEXT_SPRINT BEHOLDER_PARALYZATION_RAY ~SPIN960~
TEXT_SPRINT BEHOLDER_FINGER_OF_DEATH ~SPIN961~
TEXT_SPRINT BEHOLDER_MAGIC_MISSILE ~SPIN962~
TEXT_SPRINT VAMPIRE_BAT_FORM_CHANGE ~SPIN963~
TEXT_SPRINT VAMPIRE_GAS_FORM_CHANGE ~SPIN964~
TEXT_SPRINT TROLL_HEAL_ONE_HIT_POINT ~SPIN965~
TEXT_SPRINT TROLL_SLEEP ~SPIN966~
TEXT_SPRINT EFREETI_PHYSICAL_FORM_CHANGE ~SPIN967~
TEXT_SPRINT DOA_PHYSICAL_FORM_CHANGE ~SPIN968~
TEXT_SPRINT DJINNI_PHYSICAL_FORM_CHANGE ~SPIN969~
TEXT_SPRINT EFREETI_GAS_FORM_CHANGE ~SPIN970~
TEXT_SPRINT DOA_GAS_FORM_CHANGE ~SPIN971~
TEXT_SPRINT DJINNI_GAS_FORM_CHANGE ~SPIN972~
TEXT_SPRINT AIR_ELEMENTAL_EFFECT ~SPIN973~
TEXT_SPRINT MIND_FLAYER_PSIONIC_BLAST ~SPIN974~
TEXT_SPRINT MIND_FLAYER_DOMINATION ~SPIN975~
TEXT_SPRINT GOLEM_CONFUSION ~SPIN976~
TEXT_SPRINT GOLEM_SLOW ~SPIN977~
TEXT_SPRINT GOLEM_HASTE ~SPIN978~
TEXT_SPRINT GOLEM_GASCLOUD ~SPIN979~
TEXT_SPRINT BEHOLDER_CHARM_PERSON ~SPIN980~
TEXT_SPRINT BEHOLDER_FEAR ~SPIN981~
TEXT_SPRINT BEHOLDER_DISINTEGRATE ~SPIN982~
TEXT_SPRINT BEHOLDER_SLOW ~SPIN983~
TEXT_SPRINT BEHOLDER_FLESH_TO_STONE ~SPIN984~
TEXT_SPRINT BEHOLDER_DOMINATION ~SPIN985~
TEXT_SPRINT BEHOLDER_CAUSE_SERIOUS_WOUNDS ~SPIN986~
TEXT_SPRINT BEHOLDER_AGANNAZAR_SCORCHER ~SPIN987~
TEXT_SPRINT BEHOLDER_HOLD_PERSON ~SPIN988~
TEXT_SPRINT BEHOLDER_LIGHTNING_BOLT ~SPIN989~
TEXT_SPRINT BEHOLDER_PARALYZATION ~SPIN990~
TEXT_SPRINT BEHOLDER_DEATH_RAY ~SPIN991~
TEXT_SPRINT BEHOLDER_ANTIMAGIC_RAY ~SPIN992~
TEXT_SPRINT ACID_DAMAGE_1 ~SPIN994~
TEXT_SPRINT TANARI_DEATH_GAZE ~SPIN996~
TEXT_SPRINT TANARI_VAMPIRIC_TOUCH ~SPIN997~
TEXT_SPRINT TANARI_SILENCE ~SPIN998~
TEXT_SPRINT TANARI_PARALYZE ~SPIN999~

// Class abilities

// Blackguard

TEXT_SPRINT BLACKGUARD_ABSORB_HEALTH ~SPCL102~
TEXT_SPRINT AURA_OF_DESPAIR ~SPCL103~
TEXT_SPRINT RESIST_FEAR ~SPCL104~
TEXT_SPRINT IMMUNITY_TO_LEVEL_DRAIN ~SPCL105~
TEXT_SPRINT BLACKGUARD_ANIMATE_DEAD ~SPCL106~

// Archer

TEXT_SPRINT ARCHER_CALL_SHOT ~SPCL121~

// Kensai

TEXT_SPRINT KENSAI_KIA ~SPCL144~

// Barbarian

TEXT_SPRINT BARBARIAN_RAGE ~SPCL152~

// Paladin

TEXT_SPRINT PALADIN_LAY_ON_HANDS ~SPCL211~
TEXT_SPRINT PALADIN_DETECT_EVIL ~SPCL212~
TEXT_SPRINT PALADIN_PROTECTION_FROM_EVIL ~SPCL213~

// Cavalier

TEXT_SPRINT CAVALIER_REMOVE_FEAR ~SPCL222~

// Inquisitor

TEXT_SPRINT INQUIS_DISPEL_MAGIC ~SPCL231~
TEXT_SPRINT INQUIS_TRUE_SIGHT ~SPCL232~

// Sun Soul Monk

TEXT_SPRINT SUN_SOUL_SUN_SOULRAY ~SPCL236~
TEXT_SPRINT SUN_SOUL_GREATER_SUN ~SPCL237~
TEXT_SPRINT SUN_SOUL_SUN_SOULBEAM ~SPCL239~

// Charm Animal (Ranger)

TEXT_SPRINT RANGER_CHARM_ANIMAL ~SPCL311~

// Berserker

TEXT_SPRINT BERSERKER_RAGE ~SPCL321~

// Beastmaster

TEXT_SPRINT BEASTMASTER_FIND_FAMILIAR ~SPCL342~

// Thief

TEXT_SPRINT THIEF_SET_SNARE ~SPCL412~
TEXT_SPRINT THIEF_SET_SPECIAL_SNARE ~SPCL414~

// Assassin/Blackguard

TEXT_SPRINT ASSASSIN_POISON ~SPCL423~

// Blade

TEXT_SPRINT BLADE_OFFENSIVE_SPIN ~SPCL521~
TEXT_SPRINT BLADE_DEFENSIVE_SPIN ~SPCL522~

// Druid

TEXT_SPRINT DRUID_SHAPESHIFT_BROWNBEAR ~SPCL611~
TEXT_SPRINT DRUID_SHAPESHIFT_WOLF ~SPCL612~
TEXT_SPRINT DRUID_SHAPESHIFT_BLACKBEAR ~SPCL613~

// Totemic Druid

TEXT_SPRINT TOTEMIC_DRUID_SUMMON_SPIRIT_ANIMAL ~SPCL621~

// Avenger

TEXT_SPRINT AVENGER_SHAPESHIFT_SWORDSPIDER ~SPCL632~
TEXT_SPRINT AVENGER_SHAPESHIFT_BABYWYVERN ~SPCL633~
TEXT_SPRINT AVENGER_SHAPESHIFT_FIRESALAMANDER ~SPCL634~

// Shapeshifter

TEXT_SPRINT SHAPESHIFTER_SHAPESHIFT_WEREWOLF ~SPCL643~
TEXT_SPRINT SHAPESHIFTER_SHAPESHIFT_GREATERWEREWOLF ~SPCL644~

// Priest of Talos

TEXT_SPRINT TALOS_STORMSHIELD ~SPCL721~
TEXT_SPRINT TALOS_LIGHTNING_BOLT ~SPCL722~

// Priest of Helm

TEXT_SPRINT HELM_SEEKING_SWORD ~SPCL731~
TEXT_SPRINT HELM_TRUE_SIGHT ~SPCL732~

// Priest of Lathander

TEXT_SPRINT LATHANDER_BOON ~SPCL741~
TEXT_SPRINT LATHANDER_HOLD_UNDEAD ~SPCL742~

// Monk

TEXT_SPRINT MONK_STUNNING_BLOW ~SPCL811~
TEXT_SPRINT MONK_LAY_ON_HANDS ~SPCL815~
TEXT_SPRINT MONK_QUIVERING_PALM ~SPCL820~

// Warrior HLAs

TEXT_SPRINT WARRIOR_WHIRLWIND ~SPCL900~
TEXT_SPRINT WARRIOR_GREATER_WHIRLWIND ~SPCL901~
TEXT_SPRINT WARRIOR_DEATHBLOW ~SPCL902~
TEXT_SPRINT WARRIOR_GREATER_DEATHBLOW ~SPCL903~
TEXT_SPRINT WARRIOR_RESIST_MAGIC ~SPCL904~
TEXT_SPRINT WARRIOR_CRITICAL_STRIKE ~SPCL905~
TEXT_SPRINT WARRIOR_POWER_ATTACK ~SPCL906~
TEXT_SPRINT WARRIOR_HARDINESS ~SPCL907~
TEXT_SPRINT WARRIOR_WAR_CRY ~SPCL908~
TEXT_SPRINT WARRIOR_SMITE ~SPCL909~

// Rogue HLAs

TEXT_SPRINT ROGUE_SET_SPIKE_TRAP ~SPCL910~
TEXT_SPRINT ROGUE_SET_EXPLODING_TRAP ~SPCL911~
TEXT_SPRINT ROGUE_SET_TIME_TRAP ~SPCL912~
TEXT_SPRINT ROGUE_EVASION ~SPCL913~
TEXT_SPRINT ROGUE_GREATER_EVASION ~SPCL914~
TEXT_SPRINT ROGUE_ASSASINATION ~SPCL916~
TEXT_SPRINT ROGUE_AVOID_DEATH ~SPCL917~
TEXT_SPRINT RANGER_TRACKING ~SPCL922~

// Paladin HLA

TEXT_SPRINT PALADIN_SUMMON_DEVA ~SPCL923~

// Druid

TEXT_SPRINT DRUID_IMMUNE_POISON ~SPCL924~
TEXT_SPRINT DRUID_RESISTS ~SPCL925~

// Shadowdancer HLAs

TEXT_SPRINT SHADOWDANCER_SHADOW_TWIN ~SPCL936~
TEXT_SPRINT SHADOWDANCER_SHADOW_MAZE ~SPCL937~
TEXT_SPRINT SHADOWDANCER_SHADOW_FORM ~SPCL938~

// Shaman HLAs

TEXT_SPRINT SHAMAN_SPIRIT_FORM ~SPCL940~
TEXT_SPRINT SHAMAN_FAVORED_OF_THE_SPIRITS ~SPCL941~
