// Divine spells

// Level 1

TEXT_SPRINT CLERIC_BLESS ~SPPR101~
TEXT_SPRINT CLERIC_COMMAND ~SPPR102~
TEXT_SPRINT CLERIC_CURE_LIGHT_WOUNDS ~SPPR103~
TEXT_SPRINT CLERIC_DETECT_EVIL ~SPPR104~
TEXT_SPRINT CLERIC_ENTANGLE ~SPPR105~
TEXT_SPRINT CLERIC_MAGIC_STONE ~SPPR106~
TEXT_SPRINT CLERIC_PROTECT_FROM_EVIL ~SPPR107~
TEXT_SPRINT CLERIC_REMOVE_FEAR ~SPPR108~
TEXT_SPRINT CLERIC_SANCTUARY ~SPPR109~
TEXT_SPRINT CLERIC_SHILLELAGH ~SPPR110~
TEXT_SPRINT CLERIC_ARMOR_OF_FAITH ~SPPR111~
TEXT_SPRINT CLERIC_CURSE ~SPPR112~
TEXT_SPRINT CLERIC_DOOM ~SPPR113~
TEXT_SPRINT CLERIC_CAUSE_LIGHT_WOUNDS ~SPPR114~
TEXT_SPRINT CLERIC_SUNSCORCH ~SPPR115~
TEXT_SPRINT CLERIC_SPIRIT_WARD ~SPPR150~
TEXT_SPRINT CLERIC_PROTECT_FROM_GOOD ~SPPR199~

// Level 2

TEXT_SPRINT CLERIC_AID ~SPPR201~
TEXT_SPRINT CLERIC_BARKSKIN ~SPPR202~
TEXT_SPRINT CLERIC_CHANT ~SPPR203~
TEXT_SPRINT CLERIC_CHARM_PERSON ~SPPR204~
TEXT_SPRINT CLERIC_FIND_TRAPS ~SPPR205~
TEXT_SPRINT CLERIC_FLAME_BLADE ~SPPR206~
TEXT_SPRINT CLERIC_GOOD_BERRIES ~SPPR207~
TEXT_SPRINT CLERIC_HOLD_PERSON ~SPPR208~
TEXT_SPRINT CLERIC_KNOW_ALIGNMENT ~SPPR209~
TEXT_SPRINT CLERIC_RESIST_FIRE ~SPPR210~
TEXT_SPRINT CLERIC_SILENCE_15_FOOT ~SPPR211~
TEXT_SPRINT CLERIC_SLOW_POISON ~SPPR212~
TEXT_SPRINT CLERIC_SPIRITUAL_HAMMER ~SPPR213~
TEXT_SPRINT CLERIC_DRAW_UPON_HOLY_MIGHT ~SPPR214~
TEXT_SPRINT CLERIC_GOODBERRY ~SPPR215~
TEXT_SPRINT CLERIC_RESIST_FIRE_AND_COLD ~SPPR216~
TEXT_SPRINT CLERIC_CURE_MODERATE_WOUNDS ~SPPR217~
TEXT_SPRINT CLERIC_ALICORN_LANCE ~SPPR218~
TEXT_SPRINT CLERIC_BEAST_CLAW ~SPPR219~
TEXT_SPRINT CLERIC_CAUSE_MODERATE_WOUNDS ~SPPR220~
TEXT_SPRINT CLERIC_WRITHING_FOG ~SPPR250~

// Level 3

TEXT_SPRINT CLERIC_ANIMATE_DEAD ~SPPR301~
TEXT_SPRINT CLERIC_CALL_LIGHTNING ~SPPR302~
TEXT_SPRINT CLERIC_DISPEL_MAGIC ~SPPR303~
TEXT_SPRINT CLERIC_GLYPH_OF_WARDING ~SPPR304~
TEXT_SPRINT CLERIC_HOLD_ANIMAL ~SPPR305~
TEXT_SPRINT CLERIC_PROTECTION_FROM_FIRE ~SPPR306~
TEXT_SPRINT CLERIC_REMOVE_CURSE ~SPPR307~
TEXT_SPRINT CLERIC_REMOVE_PARALYSIS ~SPPR308~
TEXT_SPRINT CLERIC_INVISIBILITY_PURGE ~SPPR309~
TEXT_SPRINT CLERIC_MISCAST_MAGIC ~SPPR310~
TEXT_SPRINT CLERIC_RIGID_THINKING ~SPPR311~
TEXT_SPRINT CLERIC_STRENGTH_OF_ONE ~SPPR312~
TEXT_SPRINT CLERIC_HOLY_SMITE ~SPPR313~
TEXT_SPRINT CLERIC_UNHOLY_BLIGHT ~SPPR314~
TEXT_SPRINT CLERIC_CURE_MEDIUM_WOUNDS ~SPPR315~
TEXT_SPRINT CLERIC_PRAYER ~SPPR316~
TEXT_SPRINT CLERIC_CURE_DISEASE ~SPPR317~
TEXT_SPRINT CLERIC_ZONE_OF_SWEET_AIR ~SPPR318~
TEXT_SPRINT CLERIC_SUMMON_INSECTS ~SPPR319~
TEXT_SPRINT CLERIC_CAUSE_DISEASE ~SPPR320~
TEXT_SPRINT CLERIC_EXALTATION ~SPPR321~
TEXT_SPRINT CLERIC_MOONBLADE ~SPPR322~
TEXT_SPRINT CLERIC_CIRCLE_OF_BONES ~SPPR323~
TEXT_SPRINT CLERIC_SPIKE_GROWTH ~SPPR324~
TEXT_SPRINT CLERIC_CLOUDBURST ~SPPR325~
TEXT_SPRINT CLERIC_MOLD_TOUCH ~SPPR326~
TEXT_SPRINT CLERIC_STORM_SHELL ~SPPR327~
TEXT_SPRINT CLERIC_SUMMON_LIZARDMEN ~SPPR328~
TEXT_SPRINT CLERIC_SUMMON_TROLLS ~SPPR329~
TEXT_SPRINT CLERIC_CAUSE_MEDIUM_WOUNDS ~SPPR330~
TEXT_SPRINT CLERIC_FAVOR_OF_ILMATER ~SPPR331~
TEXT_SPRINT CLERIC_SPIRITUAL_CLARITY ~SPPR350~

// Level 4

TEXT_SPRINT CLERIC_CURE_SERIOUS_WOUNDS ~SPPR401~
TEXT_SPRINT CLERIC_ANIMAL_SUMMONING_1 ~SPPR402~
TEXT_SPRINT CLERIC_FREE_ACTION ~SPPR403~
TEXT_SPRINT CLERIC_NEUTRALIZE_POISON ~SPPR404~
TEXT_SPRINT CLERIC_MENTAL_DOMINATION ~SPPR405~
TEXT_SPRINT CLERIC_DEFENSIVE_HARMONY ~SPPR406~
TEXT_SPRINT CLERIC_PROTECTION_FROM_LIGHTNING ~SPPR407~
TEXT_SPRINT CLERIC_PROTECTION_FROM_EVIL_10_FOOT ~SPPR408~
TEXT_SPRINT CLERIC_DEATH_WARD ~SPPR409~
TEXT_SPRINT CLERIC_CALL_WOODLAND_BEINGS ~SPPR410~
TEXT_SPRINT CLERIC_POISON ~SPPR411~
TEXT_SPRINT CLERIC_HOLY_POWER ~SPPR412~
TEXT_SPRINT CLERIC_NEGATIVE_PLANE_PROTECTION ~SPPR413~
TEXT_SPRINT CLERIC_CAUSE_SERIOUS_WOUNDS ~SPPR414~
TEXT_SPRINT CLERIC_FAR_SIGHT ~SPPR415~
TEXT_SPRINT CLERIC_CLOAK_OF_FEAR ~SPPR416~
TEXT_SPRINT CLERIC_LESSER_RESTORATION ~SPPR417~
TEXT_SPRINT CLERIC_GIANT_INSECT ~SPPR418~
TEXT_SPRINT CLERIC_PRODUCE_FIRE ~SPPR419~
TEXT_SPRINT CLERIC_STATIC_CHARGE ~SPPR420~
TEXT_SPRINT CLERIC_RECITATION ~SPPR421~
TEXT_SPRINT CLERIC_BLOOD_RAGE ~SPPR422~
TEXT_SPRINT CLERIC_CLOUD_OF_PESTILENCE ~SPPR423~
TEXT_SPRINT CLERIC_UNFAILING_ENDURANCE ~SPPR424~
TEXT_SPRINT CLERIC_STAR_METAL_CUDGEL ~SPPR425~
TEXT_SPRINT CLERIC_SMASHING_WAVE ~SPPR426~
TEXT_SPRINT CLERIC_THORN_SPRAY ~SPPR427~
TEXT_SPRINT CLERIC_WALL_OF_MOONLIGHT ~SPPR428~
TEXT_SPRINT CLERIC_SPIRIT_FIRE ~SPPR450~

// Level 5

TEXT_SPRINT CLERIC_ANIMAL_SUMMONING_2 ~SPPR501~
TEXT_SPRINT CLERIC_CURE_CRITICAL_WOUNDS ~SPPR502~
TEXT_SPRINT CLERIC_FLAME_STRIKE ~SPPR503~
TEXT_SPRINT CLERIC_RAISE_DEAD ~SPPR504~
TEXT_SPRINT CLERIC_TRUE_SIGHT ~SPPR505~
TEXT_SPRINT CLERIC_IRONSKIN ~SPPR506~
TEXT_SPRINT CLERIC_CHAMPIONS_STRENGTH ~SPPR507~
TEXT_SPRINT CLERIC_CHAOTIC_COMMANDS ~SPPR508~
TEXT_SPRINT CLERIC_MAGIC_RESISTANCE ~SPPR509~
TEXT_SPRINT CLERIC_CAUSE_CRITICAL_WOUNDS ~SPPR510~
TEXT_SPRINT CLERIC_SLAY_LIVING ~SPPR511~
TEXT_SPRINT CLERIC_GREATER_COMMAND ~SPPR512~
TEXT_SPRINT CLERIC_RIGHTEOUS_MAGIC ~SPPR513~
TEXT_SPRINT CLERIC_MASS_CURE ~SPPR514~
TEXT_SPRINT CLERIC_REPULSE_UNDEAD ~SPPR515~
TEXT_SPRINT CLERIC_PIXIE_DUST ~SPPR516~
TEXT_SPRINT CLERIC_INSECT_PLAGUE ~SPPR517~
TEXT_SPRINT CLERIC_RIGHTEOUS_WRATH_OF_THE_FAITHFUL ~SPPR518~
TEXT_SPRINT CLERIC_SPIKE_STONES ~SPPR519~
TEXT_SPRINT CLERIC_SHIELD_OF_LATHANDER ~SPPR520~
TEXT_SPRINT CLERIC_UNDEAD_WARD ~SPPR521~
TEXT_SPRINT CLERIC_ANIMAL_RAGE ~SPPR522~
TEXT_SPRINT CLERIC_MASS_CAUSE_LIGHT_WOUNDS ~SPPR523~
TEXT_SPRINT CLERIC_RECALL_SPIRIT ~SPPR550~
TEXT_SPRINT ENEMY_CLERIC_SLAY_LIVING ~SPPR599~

// Level 6

TEXT_SPRINT CLERIC_AERIAL_SERVANT ~SPPR601~
TEXT_SPRINT CLERIC_ANIMAL_SUMMONING_3 ~SPPR602~
TEXT_SPRINT CLERIC_BLADE_BARRIER ~SPPR603~
TEXT_SPRINT CLERIC_CONJURE_ANIMALS ~SPPR604~
TEXT_SPRINT CLERIC_CONJURE_FIRE_ELEMENTAL ~SPPR605~
TEXT_SPRINT CLERIC_FIRE_SEEDS ~SPPR606~
TEXT_SPRINT CLERIC_HEAL ~SPPR607~
TEXT_SPRINT CLERIC_HARM ~SPPR608~
TEXT_SPRINT CLERIC_FALSE_DAWN ~SPPR609~
TEXT_SPRINT CLERIC_DOLOROUS_DECAY ~SPPR610~
TEXT_SPRINT CLERIC_WONDROUS_RECALL ~SPPR611~
TEXT_SPRINT CLERIC_BOLT_OF_GLORY ~SPPR612~
TEXT_SPRINT CLERIC_PHYSICAL_MIRROR ~SPPR613~
TEXT_SPRINT CLERIC_SOL_SEARING_ORB ~SPPR614~
TEXT_SPRINT CLERIC_ENTROPY_SHIELD ~SPPR615~
TEXT_SPRINT CLERIC_WHIRLWIND ~SPPR617~
TEXT_SPRINT CLERIC_SPIRITUAL_WRATH ~SPPR618~
TEXT_SPRINT CLERIC_SPIRITUAL_LOCK ~SPPR650~
TEXT_SPRINT NPC_BLADE_BARRIER ~SPPR698~
TEXT_SPRINT ENEMY_CLERIC_HARM ~SPPR699~

// Level 7

TEXT_SPRINT CLERIC_SHIELD_OF_THE_ARCHONS ~SPPR701~
TEXT_SPRINT CLERIC_CONJURE_EARTH_ELEMENTAL ~SPPR702~
TEXT_SPRINT CLERIC_GATE ~SPPR703~
TEXT_SPRINT CLERIC_NATURE_BEAUTY ~SPPR704~
TEXT_SPRINT CLERIC_FIRE_STORM ~SPPR705~
TEXT_SPRINT CLERIC_SYMBOL_FEAR ~SPPR706~
TEXT_SPRINT CLERIC_SUNRAY ~SPPR707~
TEXT_SPRINT CLERIC_FINGER_OF_DEATH ~SPPR708~
TEXT_SPRINT CLERIC_CONFUSION ~SPPR709~
TEXT_SPRINT CLERIC_HOLY_WORD ~SPPR710~
TEXT_SPRINT CLERIC_REGENERATE ~SPPR711~
TEXT_SPRINT CLERIC_RESURRECTION ~SPPR712~
TEXT_SPRINT CLERIC_RESTORATION ~SPPR713~
TEXT_SPRINT CLERIC_SYMBOL_OF_PAIN ~SPPR714~
TEXT_SPRINT CLERIC_UNHOLY_WORD ~SPPR715~
TEXT_SPRINT CLERIC_SYMBOL_OF_HOPELESSNESS ~SPPR716~
TEXT_SPRINT CLERIC_CREEPING_DOOM ~SPPR717~
TEXT_SPRINT CLERIC_SYMBOL_STUN ~SPPR718~
TEXT_SPRINT CLERIC_SYMBOL_DEATH ~SPPR719~
TEXT_SPRINT CLERIC_EARTHQUAKE ~SPPR720~
TEXT_SPRINT CLERIC_ENERGY_BLADES ~SPPR721~
TEXT_SPRINT CLERIC_STORM_OF_VENGEANCE ~SPPR722~
TEXT_SPRINT CLERIC_ELEMENTAL_SWARM ~SPPR723~
TEXT_SPRINT CLERIC_GREATER_ELEMENTAL_SWARM ~SPPR724~
TEXT_SPRINT CLERIC_GLOBE_OF_BLADES ~SPPR725~
TEXT_SPRINT CLERIC_SUMMON_DEVA ~SPPR726~
TEXT_SPRINT CLERIC_SUMMON_FALLEN_DEVA ~SPPR727~
TEXT_SPRINT CLERIC_IMPLOSION ~SPPR728~
TEXT_SPRINT CLERIC_MASS_RAISE_DEAD ~SPPR729~
TEXT_SPRINT CLERIC_AURA_OF_FLAMING_DEATH ~SPPR730~
TEXT_SPRINT CLERIC_ELEMENTAL_TRANSFORMATION_FIRE ~SPPR731~
TEXT_SPRINT CLERIC_ELEMENTAL_TRANSFORMATION_EARTH ~SPPR732~
TEXT_SPRINT CLERIC_IMPERVIOUS_SANCTITY_OF_MIND ~SPPR733~
TEXT_SPRINT CLERIC_DESTRUCTION ~SPPR734~
TEXT_SPRINT CLERIC_GREATER_SHIELD_OF_LATHANDER ~SPPR735~
TEXT_SPRINT CLERIC_MIST_OF_ELDATH ~SPPR736~
TEXT_SPRINT CLERIC_STALKER ~SPPR737~
TEXT_SPRINT CLERIC_HEAVENLY_INFERNO ~SPPR738~
TEXT_SPRINT CLERIC_ENERGY_DRAIN ~SPPR739~
TEXT_SPRINT CLERIC_WITHER ~SPPR740~
TEXT_SPRINT CLERIC_ETHER_GATE ~SPPR750~
TEXT_SPRINT CLERIC_ETHEREAL_RETRIBUTION ~SPPR751~

// Misc

TEXT_SPRINT TRAP_GLYPH_OF_WARDING ~SPPR901~
TEXT_SPRINT TRAP_DIRE_CHARM ~SPPR982~
TEXT_SPRINT TRAP_CONFUSION ~SPPR983~
TEXT_SPRINT TRAP_CHROMATIC_ORB ~SPPR984~
TEXT_SPRINT TRAP_FLAMESTRIKE ~SPPR985~
TEXT_SPRINT TRAP_MISCAST_MAGIC ~SPPR986~
TEXT_SPRINT TRAP_CALL_LIGHTNING ~SPPR987~
TEXT_SPRINT TRAP_SILENCE ~SPPR988~
TEXT_SPRINT TRAP_HOLD_PERSON ~SPPR989~
TEXT_SPRINT SHOAL_REVIVE ~SPPR999~

// Arcane spells

// Misc

TEXT_SPRINT TRAP_FIREBALL ~SPWI001~
TEXT_SPRINT TRAP_LIGHTNING_BOLT ~SPWI002~
TEXT_SPRINT TRAP_MAGIC_MISSILE ~SPWI003~
TEXT_SPRINT TRAP_STINKING_CLOUD ~SPWI004~
TEXT_SPRINT TRAP_ARROW ~SPWI005~
TEXT_SPRINT TRAP_ARROW_SLAYING ~SPWI006~
TEXT_SPRINT TRAP_ARROW_ACID ~SPWI007~
TEXT_SPRINT TRAP_ARROW_BITING ~SPWI008~
TEXT_SPRINT TRAP_ARROW_DETONATION ~SPWI009~
TEXT_SPRINT TRAP_ARROW_DISPELLING ~SPWI010~
TEXT_SPRINT TRAP_ARROW_FIRE ~SPWI011~
TEXT_SPRINT TRAP_ARROW_ICE ~SPWI012~
TEXT_SPRINT TRAP_ARROW_PIERCING ~SPWI013~
TEXT_SPRINT TRAP_MONSTER_SUMMONING ~SPWI014~
TEXT_SPRINT TRAP_FROST ~SPWI015~
TEXT_SPRINT TRAP_CLOUDKILL ~SPWI016~
TEXT_SPRINT TRAP_MINOR_LIGHTNING_BOLT ~SPWI017~
TEXT_SPRINT TRAP_DISEASE_DARTS ~SPWI018~
TEXT_SPRINT TRAP_POISON_DAMAGE_DARTS ~SPWI019~
TEXT_SPRINT TRAP_UNDERWATER_BITE ~SPWI020~
TEXT_SPRINT TRAP_HALLWAY_SPIKES ~SPWI021~
TEXT_SPRINT TRAP_MUCK ~SPWI022~
TEXT_SPRINT TRAP_SHADOW_DEATH ~SPWI023~
TEXT_SPRINT TRAP_GUILLOTINE ~SPWI024~
TEXT_SPRINT TRAP_LIGHTNING_ORB1 ~SPWI025~
TEXT_SPRINT TRAP_LIGHTNING_ORB2 ~SPWI026~
TEXT_SPRINT TRAP_LIGHTNING_ORB3 ~SPWI027~
TEXT_SPRINT TRAP_POISON_PARALYZATION_DARTS ~SPWI028~
TEXT_SPRINT TRAP_POISON_CONFUSION_DARTS ~SPWI029~
TEXT_SPRINT TRAP_DEATH_FOG ~SPWI030~
TEXT_SPRINT TRAP_FINGER_OF_DEATH ~SPWI031~
TEXT_SPRINT TRAP_SLEEP ~SPWI032~
TEXT_SPRINT TRAP_MAGIC_MISSILE_5 ~SPWI033~
TEXT_SPRINT TRAP_FIREBALL_4D6 ~SPWI034~
TEXT_SPRINT TRAP_FLESH_TO_STONE ~SPWI035~
TEXT_SPRINT TRAP_HORROR ~SPWI036~
TEXT_SPRINT WIZARD_CHAOS_VISUALS_ONLY ~SPWI050~
TEXT_SPRINT WIZARD_DISPEL_MAGIC_VISUALS_ONLY ~SPWI051~
TEXT_SPRINT WIZARD_POWER_WORD_SILENCE_VISUALS_ONLY ~SPWI052~
TEXT_SPRINT WIZARD_FLESH_TO_STONE_IGNORE_RESISTANCE ~SPWI053~
TEXT_SPRINT WIZARD_FINGER_OF_DEATH_IGNORE_RESISTANCE ~SPWI054~
TEXT_SPRINT WIZARD_DISINTEGRATE_IGNORE_RESISTANCE ~SPWI055~
TEXT_SPRINT WIZARD_DISINTEGRATE2_IGNORE_RESISTANCE ~SPWI056~

// Level 1

TEXT_SPRINT WIZARD_GREASE ~SPWI101~
TEXT_SPRINT WIZARD_ARMOR ~SPWI102~
TEXT_SPRINT WIZARD_BURNING_HANDS ~SPWI103~
TEXT_SPRINT WIZARD_CHARM_PERSON ~SPWI104~
TEXT_SPRINT WIZARD_COLOR_SPRAY ~SPWI105~
TEXT_SPRINT WIZARD_BLIND_OLD ~SPWI106~
TEXT_SPRINT WIZARD_FRIENDS ~SPWI107~
TEXT_SPRINT WIZARD_PFP_OLD ~SPWI108~
TEXT_SPRINT WIZARD_IDENTIFY ~SPWI110~
TEXT_SPRINT WIZARD_INFRAVISION ~SPWI111~
TEXT_SPRINT WIZARD_MAGIC_MISSILE ~SPWI112~
TEXT_SPRINT WIZARD_PROTECTION_FROM_EVIL ~SPWI113~
TEXT_SPRINT WIZARD_SHIELD ~SPWI114~
TEXT_SPRINT WIZARD_SHOCKING_GRASP ~SPWI115~
TEXT_SPRINT WIZARD_SLEEP ~SPWI116~
TEXT_SPRINT WIZARD_CHILL_TOUCH ~SPWI117~
TEXT_SPRINT WIZARD_CHROMATIC_ORB ~SPWI118~
TEXT_SPRINT WIZARD_LARLOCH_MINOR_DRAIN ~SPWI119~
TEXT_SPRINT WIZARD_REFLECTED_IMAGE ~SPWI120~
TEXT_SPRINT WIZARD_FIND_FAMILAR ~SPWI123~
TEXT_SPRINT WIZARD_NAHALS_RECKLESS_DWEOMER ~SPWI124~
TEXT_SPRINT WIZARD_SPOOK ~SPWI125~
TEXT_SPRINT WIZARD_EXPEDITIOUS_RETREAT ~SPWI126~

// Level 2

TEXT_SPRINT WIZARD_BLUR ~SPWI201~
TEXT_SPRINT WIZARD_DETECT_EVIL ~SPWI202~
TEXT_SPRINT WIZARD_DETECT_INVISIBILITY ~SPWI203~
TEXT_SPRINT WIZARD_SNILLOCS_SNOWBALL_SWARM ~SPWI204~
TEXT_SPRINT WIZARD_HORROR ~SPWI205~
TEXT_SPRINT WIZARD_INVISIBILITY ~SPWI206~
TEXT_SPRINT WIZARD_KNOCK ~SPWI207~
TEXT_SPRINT WIZARD_KNOW_ALIGNMENT ~SPWI208~
TEXT_SPRINT WIZARD_LUCK ~SPWI209~
TEXT_SPRINT WIZARD_RESIST_FEAR ~SPWI210~
TEXT_SPRINT WIZARD_MELF_ACID_ARROW ~SPWI211~
TEXT_SPRINT WIZARD_MIRROR_IMAGE ~SPWI212~
TEXT_SPRINT WIZARD_STINKING_CLOUD ~SPWI213~
TEXT_SPRINT WIZARD_STRENGTH ~SPWI214~
TEXT_SPRINT WIZARD_WEB ~SPWI215~
TEXT_SPRINT WIZARD_DECASTAVE ~SPWI216~
TEXT_SPRINT WIZARD_AGANNAZAR_SCORCHER ~SPWI217~
TEXT_SPRINT WIZARD_GHOUL_TOUCH ~SPWI218~
TEXT_SPRINT WIZARD_VOCALIZE ~SPWI219~
TEXT_SPRINT WIZARD_POWER_WORD_SLEEP ~SPWI220~
TEXT_SPRINT WIZARD_RAY_OF_ENFEEBLEMENT ~SPWI221~
TEXT_SPRINT WIZARD_CHAOS_SHIELD ~SPWI222~
TEXT_SPRINT WIZARD_DEAFNESS ~SPWI223~
TEXT_SPRINT WIZARD_GLITTERDUST ~SPWI224~
TEXT_SPRINT WIZARD_CATS_GRACE ~SPWI225~
TEXT_SPRINT WIZARD_BLINDNESS ~SPWI226~
TEXT_SPRINT WIZARD_PROTECTION_FROM_PETRIFICATION ~SPWI227~
TEXT_SPRINT CONTINGENCY_MIRROR_IMAGE ~SPWI298~

// Level 3

TEXT_SPRINT WIZARD_CLAIRVOYANCE ~SPWI301~
TEXT_SPRINT WIZARD_DISPEL_MAGIC ~SPWI302~
TEXT_SPRINT WIZARD_FLAME_ARROW ~SPWI303~
TEXT_SPRINT WIZARD_FIREBALL ~SPWI304~
TEXT_SPRINT WIZARD_HASTE ~SPWI305~
TEXT_SPRINT WIZARD_HOLD_PERSON ~SPWI306~
TEXT_SPRINT WIZARD_INVISIBILITY_10_FOOT ~SPWI307~
TEXT_SPRINT WIZARD_LIGHTNING_BOLT ~SPWI308~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_1 ~SPWI309~
TEXT_SPRINT WIZARD_NON_DETECTION ~SPWI310~
TEXT_SPRINT WIZARD_PROTECTION_FROM_NORMAL_MISSILES ~SPWI311~
TEXT_SPRINT WIZARD_SLOW ~SPWI312~
TEXT_SPRINT WIZARD_SKULL_TRAP ~SPWI313~
TEXT_SPRINT WIZARD_VAMPIRIC_TOUCH ~SPWI314~
TEXT_SPRINT WIZARD_WRAITH_FORM ~SPWI315~
TEXT_SPRINT WIZARD_DIRE_CHARM ~SPWI316~
TEXT_SPRINT WIZARD_GHOST_ARMOR ~SPWI317~
TEXT_SPRINT WIZARD_MINOR_SPELL_DEFLECTION ~SPWI318~
TEXT_SPRINT WIZARD_PROTECTION_FROM_FIRE ~SPWI319~
TEXT_SPRINT WIZARD_PROTECTION_FROM_COLD ~SPWI320~
TEXT_SPRINT WIZARD_SPELL_THRUST ~SPWI321~
TEXT_SPRINT WIZARD_DETECT_ILLUSION ~SPWI322~
TEXT_SPRINT WIZARD_TRUE_DISPEL_MAGIC ~SPWI323~
TEXT_SPRINT WIZARD_HOLD_UNDEAD ~SPWI324~
TEXT_SPRINT WIZARD_MELF_METEOR ~SPWI325~
TEXT_SPRINT WIZARD_ICELANCE ~SPWI327~
TEXT_SPRINT WIZARD_LANCE_OF_DISRUPTION ~SPWI328~

// Level 4

TEXT_SPRINT WIZARD_CONFUSION ~SPWI401~
TEXT_SPRINT WIZARD_DIMENSION_DOOR ~SPWI402~
TEXT_SPRINT WIZARD_FIRE_SHIELD_BLUE ~SPWI403~
TEXT_SPRINT WIZARD_ICE_STORM ~SPWI404~
TEXT_SPRINT WIZARD_IMPROVED_INVISIBILITY ~SPWI405~
TEXT_SPRINT WIZARD_MINOR_GLOBE_OF_INVULNERABILITY ~SPWI406~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_2 ~SPWI407~
TEXT_SPRINT WIZARD_STONE_SKIN ~SPWI408~
TEXT_SPRINT WIZARD_CONTAGION ~SPWI409~
TEXT_SPRINT WIZARD_REMOVE_CURSE ~SPWI410~
TEXT_SPRINT WIZARD_EMOTION_HOPELESSNESS ~SPWI411~
TEXT_SPRINT WIZARD_GREATER_MALISON ~SPWI412~
TEXT_SPRINT WIZARD_OTILUKES_RESILIENT_SPHERE ~SPWI413~
TEXT_SPRINT WIZARD_SPIRIT_ARMOR ~SPWI414~
TEXT_SPRINT WIZARD_POLYMORPH_OTHER ~SPWI415~
TEXT_SPRINT WIZARD_POLYMORPH_SELF ~SPWI416~
TEXT_SPRINT WIZARD_ENCHANTED_WEAPON ~SPWI417~
TEXT_SPRINT WIZARD_FIRE_SHIELD_RED ~SPWI418~
TEXT_SPRINT WIZARD_SECRET_WORD ~SPWI419~
TEXT_SPRINT WIZARD_MINOR_SEQUENCER ~SPWI420~
TEXT_SPRINT WIZARD_TELEPORT_FIELD ~SPWI421~
TEXT_SPRINT WIZARD_BELTYNS_BURNING_BLOOD ~SPWI422~
TEXT_SPRINT WIZARD_SPIDER_SPAWN ~SPWI423~
TEXT_SPRINT WIZARD_FAR_SIGHT ~SPWI424~
TEXT_SPRINT WIZARD_EYE ~SPWI425~
TEXT_SPRINT WIZARD_SHADOW_MONSTERS ~SPWI426~
TEXT_SPRINT WIZARD_EMOTION_COURAGE ~SPWI427~
TEXT_SPRINT WIZARD_EMOTION_FEAR ~SPWI428~
TEXT_SPRINT WIZARD_EMOTION_HOPE ~SPWI429~
TEXT_SPRINT WIZARD_MORDENKAINENS_FORCE_MISSILES ~SPWI430~
TEXT_SPRINT WIZARD_SHOUT ~SPWI431~
TEXT_SPRINT WIZARD_VITRIOLIC_SPHERE ~SPWI432~
TEXT_SPRINT WIZARD_POLYMORPH_BORING_BEETLE ~SPWI480~
TEXT_SPRINT WIZARD_POLYMORPH_POLAR_BEAR ~SPWI481~
TEXT_SPRINT WIZARD_POLYMORPH_WINTER_WOLF ~SPWI482~
TEXT_SPRINT WIZARD_POLYMORPH_NATURAL_FORM ~SPWI490~
TEXT_SPRINT WIZARD_POLYMORPH_FLIND ~SPWI493~
TEXT_SPRINT WIZARD_POLYMORPH_OGRE ~SPWI494~
TEXT_SPRINT WIZARD_POLYMORPH_SPIDER ~SPWI495~
TEXT_SPRINT WIZARD_POLYMORPH_MUSTARD_JELLY ~SPWI496~
TEXT_SPRINT WIZARD_POLYMORPH_BROWN_BEAR ~SPWI497~
TEXT_SPRINT WIZARD_POLYMORPH_BLACK_BEAR ~SPWI498~
TEXT_SPRINT WIZARD_POLYMORPH_WOLF ~SPWI499~

// Level 5

TEXT_SPRINT WIZARD_ANIMATE_DEAD ~SPWI501~
TEXT_SPRINT WIZARD_CLOUDKILL ~SPWI502~
TEXT_SPRINT WIZARD_CONE_OF_COLD ~SPWI503~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_3 ~SPWI504~
TEXT_SPRINT WIZARD_SHADOW_DOOR ~SPWI505~
TEXT_SPRINT WIZARD_DOMINATION ~SPWI506~
TEXT_SPRINT WIZARD_HOLD_MONSTER ~SPWI507~
TEXT_SPRINT WIZARD_CHAOS ~SPWI508~
TEXT_SPRINT WIZARD_FEEBLEMIND ~SPWI509~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY ~SPWI510~
TEXT_SPRINT WIZARD_PROTECTION_FROM_NORMAL_WEAPONS ~SPWI511~
TEXT_SPRINT WIZARD_PROTECTION_FROM_ELECTRICITY ~SPWI512~
TEXT_SPRINT WIZARD_BREACH ~SPWI513~
TEXT_SPRINT WIZARD_LOWER_RESISTANCE ~SPWI514~
TEXT_SPRINT WIZARD_ORACLE ~SPWI515~
TEXT_SPRINT WIZARD_CONJURE_LESSER_FIRE_ELEMENTAL ~SPWI516~
TEXT_SPRINT WIZARD_PROTECTION_FROM_ACID ~SPWI517~
TEXT_SPRINT WIZARD_PHANTOM_BLADE ~SPWI518~
TEXT_SPRINT WIZARD_SPELL_SHIELD ~SPWI519~
TEXT_SPRINT WIZARD_CONJURE_LESSER_AIR_ELEMENTAL ~SPWI520~
TEXT_SPRINT WIZARD_CONJURE_LESSER_EARTH_ELEMENTAL ~SPWI521~
TEXT_SPRINT WIZARD_MINOR_SPELL_TURNING ~SPWI522~
TEXT_SPRINT WIZARD_SUN_FIRE ~SPWI523~
TEXT_SPRINT WIZARD_SHROUD_OF_FLAME ~SPWI524~
TEXT_SPRINT WIZARD_DEMI_SHADOW_MONSTERS ~SPWI525~
TEXT_SPRINT WIZARD_SUMMON_SHADOW ~SPWI526~
TEXT_SPRINT WIZARD_CWE_OLD ~SPWI527~
TEXT_SPRINT WIZARD_CONTACT_OTHER_PLANE ~SPWI528~
TEXT_SPRINT WIZARD_CONJURE_EARTH_ELEMENTAL_MALAVON ~SPWI529~
TEXT_SPRINT WIZARD_ANIMATE_DEAD_LICH ~SPWI530~
TEXT_SPRINT WIZARD_CONJURE_FIRE_ELEMENTAL ~SPWI531~
TEXT_SPRINT WIZARD_CONJURE_EARTH_ELEMENTAL ~SPWI532~
TEXT_SPRINT WIZARD_CONJURE_WATER_ELEMENTAL ~SPWI533~
TEXT_SPRINT WIZARD_CONJURE_AIR_ELEMENTAL ~SPWI534~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_ABJURATION ~SPWI590~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_CONJURATION ~SPWI591~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_DIVINATION ~SPWI592~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_ENCHANTMENT ~SPWI593~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_ILLUSIONIST ~SPWI594~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_INVOCATION ~SPWI595~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_NECROMANCY ~SPWI596~
TEXT_SPRINT WIZARD_SPELL_IMMUNITY_ALTERATION ~SPWI597~

// Level 6

TEXT_SPRINT WIZARD_INVISIBLE_STALKER ~SPWI601~
TEXT_SPRINT WIZARD_GLOBE_OF_INVULNERABILITY ~SPWI602~
TEXT_SPRINT WIZARD_TENSERS_TRANSFORMATION ~SPWI603~
TEXT_SPRINT WIZARD_FLESH_TO_STONE ~SPWI604~
TEXT_SPRINT WIZARD_DEATH_SPELL ~SPWI605~
TEXT_SPRINT WIZARD_PROTECTION_FROM_MAGIC_ENERGY ~SPWI606~
TEXT_SPRINT WIZARD_MISLEAD ~SPWI607~
TEXT_SPRINT WIZARD_PIERCE_MAGIC ~SPWI608~
TEXT_SPRINT WIZARD_TRUE_SIGHT ~SPWI609~
TEXT_SPRINT WIZARD_ANTIMAGIC_SHELL ~SPWI610~
TEXT_SPRINT WIZARD_PROTECTION_FROM_MAGIC_WEAPONS ~SPWI611~
TEXT_SPRINT WIZARD_POWER_WORD_SILENCE ~SPWI612~
TEXT_SPRINT WIZARD_IMPROVED_HASTE ~SPWI613~
TEXT_SPRINT WIZARD_DEATH_FOG ~SPWI614~
TEXT_SPRINT WIZARD_CHAIN_LIGHTNING ~SPWI615~
TEXT_SPRINT WIZARD_DISINTEGRATE ~SPWI616~
TEXT_SPRINT WIZARD_CONTINGENCY ~SPWI617~
TEXT_SPRINT WIZARD_SPELL_DEFLECTION ~SPWI618~
TEXT_SPRINT WIZARD_WYVERN_CALL ~SPWI619~
TEXT_SPRINT WIZARD_CFE_OLD ~SPWI620~
TEXT_SPRINT WIZARD_CAE_OLD ~SPWI621~
TEXT_SPRINT WIZARD_CEE_OLD ~SPWI622~
TEXT_SPRINT WIZARD_CARRION ~SPWI623~
TEXT_SPRINT WIZARD_SUMMON_NISHRUU ~SPWI624~
TEXT_SPRINT WIZARD_STONE_TO_FLESH ~SPWI625~
TEXT_SPRINT WIZARD_LICH_TOUCH ~SPWI626~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_4 ~SPWI627~
TEXT_SPRINT WIZARD_OTILUKES_FREEZING_SPHERE ~SPWI628~
TEXT_SPRINT WIZARD_SHADES ~SPWI629~
TEXT_SPRINT WIZARD_DARTS_OF_BONE ~SPWI630~
TEXT_SPRINT WIZARD_SOUL_EATER ~SPWI631~
TEXT_SPRINT WIZARD_TROLLISH_FORTITUDE ~SPWI632~

// Level 7

TEXT_SPRINT WIZARD_SPELL_TURNING ~SPWI701~
TEXT_SPRINT WIZARD_PROTECTION_FROM_THE_ELEMENTS ~SPWI702~
TEXT_SPRINT WIZARD_PROJECT_IMAGE ~SPWI703~
TEXT_SPRINT WIZARD_RUBY_RAY_OF_REVERSAL ~SPWI704~
TEXT_SPRINT WIZARD_WARDING_WHIP ~SPWI705~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_5 ~SPWI706~
TEXT_SPRINT WIZARD_CACOFIEND ~SPWI707~
TEXT_SPRINT WIZARD_MANTLE ~SPWI708~
TEXT_SPRINT WIZARD_MALAVONS_RAGE ~SPWI709~
TEXT_SPRINT WIZARD_SPELL_SEQUENCER ~SPWI710~
TEXT_SPRINT WIZARD_SPHERE_OF_CHAOS ~SPWI711~
TEXT_SPRINT WIZARD_DELAYED_BLAST_FIREBALL ~SPWI712~
TEXT_SPRINT WIZARD_FINGER_OF_DEATH ~SPWI713~
TEXT_SPRINT WIZARD_PRISMATIC_SPRAY ~SPWI714~
TEXT_SPRINT WIZARD_POWER_WORD_STUN ~SPWI715~
TEXT_SPRINT WIZARD_MORDENKAINENS_SWORD ~SPWI716~
TEXT_SPRINT WIZARD_SUMMON_EFREET ~SPWI717~
TEXT_SPRINT WIZARD_SUMMON_DJINNI ~SPWI718~
TEXT_SPRINT WIZARD_SUMMON_HAKEASHAR ~SPWI719~
TEXT_SPRINT WIZARD_CONTROL_UNDEAD ~SPWI720~
TEXT_SPRINT WIZARD_MASS_INVISIBILITY ~SPWI721~
TEXT_SPRINT WIZARD_LIMITED_WISH ~SPWI722~
TEXT_SPRINT WIZARD_IMPROVED_CHAOS_SHIELD ~SPWI723~
TEXT_SPRINT WIZARD_ACID_STORM ~SPWI724~
TEXT_SPRINT WIZARD_SEVEN_EYES ~SPWI725~
TEXT_SPRINT WIZARD_SUFFOCATE ~SPWI726~

// Level 8

TEXT_SPRINT WIZARD_MONSTER_SUMMONING_6 ~SPWI801~
TEXT_SPRINT WIZARD_MIND_BLANK ~SPWI802~
TEXT_SPRINT WIZARD_PROTECTION_FROM_ENERGY ~SPWI803~
TEXT_SPRINT WIZARD_SIMULACRUM ~SPWI804~
TEXT_SPRINT WIZARD_PIERCE_SHIELD ~SPWI805~
TEXT_SPRINT WIZARD_GREAT_SHOUT ~SPWI806~
TEXT_SPRINT WIZARD_SUMMON_FIEND ~SPWI807~
TEXT_SPRINT WIZARD_IMPROVED_MANTLE ~SPWI808~
TEXT_SPRINT WIZARD_SPELL_TRIGGER ~SPWI809~
TEXT_SPRINT WIZARD_INCENDIARY_CLOUD ~SPWI810~
TEXT_SPRINT WIZARD_SYMBOL_FEAR ~SPWI811~
TEXT_SPRINT WIZARD_ABI_DALZIMS_HORRID_WILTING ~SPWI812~
TEXT_SPRINT WIZARD_MAZE ~SPWI813~
TEXT_SPRINT WIZARD_IRON_BODY ~SPWI814~
TEXT_SPRINT WIZARD_POWER_WORD_BLIND ~SPWI815~
TEXT_SPRINT WIZARD_SYMBOL_STUN ~SPWI816~
TEXT_SPRINT WIZARD_SYMBOL_DEATH ~SPWI817~
TEXT_SPRINT WIZARD_BIGBYS_CLENCHED_FIST ~SPWI818~
TEXT_SPRINT WIZARD_MONSTER_SUMMONING_VI_MALAVON ~SPWI819~
TEXT_SPRINT FORCE_DAMAGE_1 ~SPWI888~
TEXT_SPRINT WIZARD_NPC_SYMBOL_DEATH ~SPWI897~
TEXT_SPRINT WIZARD_NPC_SYMBOL_STUN ~SPWI898~
TEXT_SPRINT WIZARD_NPC_SYMBOL_FEAR ~SPWI899~

// Level 9

TEXT_SPRINT WIZARD_MONSTER_SUMMONING_7 ~SPWI901~
TEXT_SPRINT WIZARD_SPELL_TRAP ~SPWI902~
TEXT_SPRINT WIZARD_SPELL_STRIKE ~SPWI903~
TEXT_SPRINT WIZARD_MALAVONS_CORROSIVE_FOG ~SPWI904~
TEXT_SPRINT WIZARD_GATE ~SPWI905~
TEXT_SPRINT WIZARD_ABSOLUTE_IMMUNITY ~SPWI907~
TEXT_SPRINT WIZARD_CHAIN_CONTINGENCY ~SPWI908~
TEXT_SPRINT WIZARD_TIME_STOP ~SPWI909~
TEXT_SPRINT WIZARD_IMPRISONMENT ~SPWI910~
TEXT_SPRINT WIZARD_METEOR_SWARM ~SPWI911~
TEXT_SPRINT WIZARD_POWER_WORD_KILL ~SPWI912~
TEXT_SPRINT WIZARD_WAIL_OF_THE_BANSHEE ~SPWI913~
TEXT_SPRINT WIZARD_ENERGY_DRAIN ~SPWI914~
TEXT_SPRINT WIZARD_BLACK_BLADE_OF_DISASTER ~SPWI915~
TEXT_SPRINT WIZARD_SHAPECHANGE ~SPWI916~
TEXT_SPRINT WIZARD_FREEDOM ~SPWI917~
TEXT_SPRINT WIZARD_BIGBYS_CRUSHING_HAND ~SPWI918~
TEXT_SPRINT WIZARD_WISH ~SPWI919~
TEXT_SPRINT WIZARD_ENERGY_BLADES ~SPWI920~
TEXT_SPRINT WIZARD_IMPROVED_ALACRITY ~SPWI921~
TEXT_SPRINT WIZARD_DRAGONS_BREATH ~SPWI922~
TEXT_SPRINT WIZARD_SUMMON_PLANATAR_GOOD ~SPWI923~
TEXT_SPRINT WIZARD_SUMMON_PLANATAR_EVIL ~SPWI924~
TEXT_SPRINT WIZARD_COMET ~SPWI925~
TEXT_SPRINT DRYAD_TELEPORT ~SPWI995~

// Innate abilities

// Seven Eyes

TEXT_SPRINT SEVEN_EYES_MIND ~SPIN107~
TEXT_SPRINT SEVEN_EYES_SWORD ~SPIN108~
TEXT_SPRINT SEVEN_EYES_MAGE ~SPIN109~
TEXT_SPRINT SEVEN_EYES_VENOM ~SPIN110~
TEXT_SPRINT SEVEN_EYES_SPIRIT ~SPIN111~
TEXT_SPRINT SEVEN_EYES_FORTITUDE ~SPIN112~
TEXT_SPRINT SEVEN_EYES_STONE ~SPIN113~

// Misc

TEXT_SPRINT INNATE_WIND_WALK ~SPIN114~
TEXT_SPRINT INNATE_MOURNFUL_WAIL ~SPIN115~
TEXT_SPRINT INNATE_DEATH_KNELL ~SPIN116~
TEXT_SPRINT INNATE_WAR_CRY ~SPIN117~
TEXT_SPRINT INNATE_UNDYING_LAMENT ~SPIN118~
TEXT_SPRINT INNATE_GREAT_ROAR ~SPIN119~
TEXT_SPRINT INNATE_RETRIBUTION ~SPIN120~
TEXT_SPRINT INNATE_SHAPESHIFTS_WEREWOLF ~SPIN121~
TEXT_SPRINT AVENGER_SHAPESHIFT_NATURAL_FORM ~SPIN122~
TEXT_SPRINT DRUID_HUMAN_FORM ~SPIN123~
TEXT_SPRINT SHAPESHIFTER_SHAPESHIFT_NATURAL_FORM ~SPIN124~
TEXT_SPRINT INNATE_WEREWOLF_DEATH ~SPIN125~
TEXT_SPRINT INNATE_WYLFDENES_DEATH_ANIMATION ~SPIN126~
TEXT_SPRINT INNATE_ICE_GOLEM_DISAPPEAR ~SPIN127~
TEXT_SPRINT INNATE_FROST_AURA ~SPIN128~
TEXT_SPRINT INNATE_SEER_TELEPORT ~SPIN129~
TEXT_SPRINT INNATE_BLUE_GLOW ~SPIN130~
TEXT_SPRINT INNATE_DRAGON_DEATH_ANIMATION ~SPIN131~
TEXT_SPRINT INNATE_DRAGON_WING_BUFFET ~SPIN132~
TEXT_SPRINT INNATE_DRAGON_GEM_EFFECTS ~SPIN133~
TEXT_SPRINT INNATE_DRAGON_BREATH ~SPIN134~
TEXT_SPRINT INNATE_DRAGON_GEM_SUMMONING ~SPIN135~
TEXT_SPRINT INNATE_BEHOLDER_UNUSED ~SPIN136~
TEXT_SPRINT INNATE_BEHOLDER_ANTIMAGIC_RAY ~SPIN137~
TEXT_SPRINT INNATE_HARPY_WAIL ~SPIN138~
TEXT_SPRINT INNATE_HARPY_WAIL_INTERNAL ~SPIN139~
TEXT_SPRINT INNATE_CRYPT_THING_TELEPORT ~SPIN140~
TEXT_SPRINT INNATE_BEHOLDER_CHARM_PERSON ~SPIN141~
TEXT_SPRINT INNATE_BEHOLDER_SLEEP ~SPIN142~
TEXT_SPRINT INNATE_BEHOLDER_FLESH_TO_STONE ~SPIN143~
TEXT_SPRINT INNATE_BEHOLDER_DISINTEGRATE ~SPIN144~
TEXT_SPRINT INNATE_BEHOLDER_FEAR ~SPIN145~
TEXT_SPRINT INNATE_BEHOLDER_SLOW ~SPIN146~
TEXT_SPRINT INNATE_BEHOLDER_CAUSE_SERIOUS_WOUNDS ~SPIN147~
TEXT_SPRINT INNATE_BEHOLDER_DEATH_RAY ~SPIN148~
TEXT_SPRINT INNATE_POLYMORPH_TO_DOG ~SPIN149~
TEXT_SPRINT SHAPESHIFT_NATURAL_FORM_1 ~SPIN150~
TEXT_SPRINT SHAPESHIFT_NATURAL_FORM_2 ~SPIN151~
TEXT_SPRINT SHAPECHANGE_MIND_FLAYER ~SPIN152~
TEXT_SPRINT SHAPECHANGE_IRON_GOLEM ~SPIN153~
TEXT_SPRINT SHAPECHANGE_GIANT_TROLL ~SPIN154~
TEXT_SPRINT SHAPECHANGE_GREATER_WOLFWERE ~SPIN155~
TEXT_SPRINT SHAPECHANGE_FIRE_ELEMENTAL ~SPIN156~
TEXT_SPRINT SHAPECHANGE_EARTH_ELEMENTAL ~SPIN157~
TEXT_SPRINT INNATE_SUMMON_GLABREZU ~SPIN158~
TEXT_SPRINT INNATE_JACKALWERE_GAZE ~SPIN159~
TEXT_SPRINT SALAMANDER_BREATHE_FIREBALL ~SPIN160~
TEXT_SPRINT INNATE_JACKALWERE_GAZE_INTERNAL ~SPIN161~
TEXT_SPRINT INNATE_HOBART_TO_RAKSHASA ~SPIN162~
TEXT_SPRINT INNATE_TELEPORT_WITHOUT_ERROR ~SPIN163~
TEXT_SPRINT INNATE_MUSTARD_JELLY_VAPOR ~SPIN164~
TEXT_SPRINT INNATE_CONTAINER_GLOW ~SPIN166~
TEXT_SPRINT INNATE_CONTAINER_GLOW_BAD ~SPIN167~
TEXT_SPRINT INNATE_CORNUGON_SUMMON_TRAVEL_ANIMATION ~SPIN168~
TEXT_SPRINT INNATE_WINTER_WOLF_BREATH ~SPIN169~
TEXT_SPRINT INNATE_REMOVE_TERIKANS_ITEM_ANIMATION ~SPIN170~
TEXT_SPRINT INNATE_BELHIFETS_DEATH_ANIMATION ~SPIN171~
TEXT_SPRINT INNATE_EVERARDS_PORTAL_CLOSING ~SPIN172~
TEXT_SPRINT INNATE_AURA_OF_FEAR ~SPIN173~
TEXT_SPRINT IWD_UNKNOWN_2 ~SPIN174~
TEXT_SPRINT IWD_UNKNOWN_3 ~SPIN175~
TEXT_SPRINT INNATE_INFERNAL_CONVEYANCE ~SPIN176~
TEXT_SPRINT INNATE_POQUELINS_PORTAL_OPENING ~SPIN177~
TEXT_SPRINT INNATE_INCENDIARY_CLOUD_IDLING ~SPIN180~
TEXT_SPRINT INNATE_INCENDIARY_CLOUD_EXPLOSION ~SPIN181~
TEXT_SPRINT INNATE_FLASH_DESTROY_SUMMON_YXUNOMEI ~SPIN182~
TEXT_SPRINT INNATE_FLASH_DESTROY_SUMMON_BELHIFET ~SPIN183~
TEXT_SPRINT INNATE_FLASH_DISAPPEAR ~SPIN184~
TEXT_SPRINT INNATE_D5_HIGH_BAPTISM ~SPIN185~
TEXT_SPRINT INNATE_PHASE_SPIDER_TELEPORT ~SPIN186~
TEXT_SPRINT INNATE_SALAMANDER_AURA_SHIKATA ~SPIN187~
TEXT_SPRINT INNATE_MYCONID_SPORES ~SPIN188~
TEXT_SPRINT INNATE_IRON_GOLEM_CLOUD ~SPIN189~
TEXT_SPRINT INNATE_ZOMBIE_LORD_AURA ~SPIN190~
TEXT_SPRINT INNATE_BOMBARDIER_BEETLE_CLOUD ~SPIN191~
TEXT_SPRINT INNATE_UMBER_HULK_GAZE ~SPIN192~
TEXT_SPRINT INNATE_SALAMANDER_AURA_FROST ~SPIN193~
TEXT_SPRINT INNATE_SALAMANDER_AURA_FIRE ~SPIN194~
TEXT_SPRINT INNATE_SHADOW_PACT ~SPIN195~
TEXT_SPRINT INNATE_CHAMELEON_POWER ~SPIN196~
TEXT_SPRINT INNATE_ANIMAL_AFFINITY ~SPIN197~
TEXT_SPRINT SHAPECHANGE_WATER_ELEMENTAL ~SPIN198~
TEXT_SPRINT POOF_GONE ~SPIN660~
TEXT_SPRINT WISH_SPELL_FAILURE ~SPIN731~
TEXT_SPRINT WISH_LOSE_SPELL ~SPIN732~
TEXT_SPRINT WISH_POISON ~SPIN733~
TEXT_SPRINT WISH_HEAL_PARTY ~SPIN734~
TEXT_SPRINT WISH_RABBIT ~SPIN735~
TEXT_SPRINT WISH_GLOBE ~SPIN736~
TEXT_SPRINT WISH_MEMORIZE ~SPIN737~
TEXT_SPRINT WISH_PLANE ~SPIN738~
TEXT_SPRINT RESTORE_FULL_HEALTH ~SPIN746~
TEXT_SPRINT RESTORE_FULL_HEALTH_PARTY ~SPIN747~
TEXT_SPRINT MIND_CRIPPLE ~SPIN802~
TEXT_SPRINT THIEF_DETECT_ILLUSION ~SPIN805~
TEXT_SPRINT END_EXPLORE ~SPIN871~
TEXT_SPRINT UNPAUSE_CASTER ~SPIN873~
TEXT_SPRINT DO_NOTHING ~SPIN905~
TEXT_SPRINT GENIE_LIMITED_WISH_HEAL_ALL ~SPIN923~
TEXT_SPRINT MEPHIT_GLASS_DUST ~SPIN935~
TEXT_SPRINT EFREETI_PHYSICAL_FORM_CHANGE ~SPIN967~
TEXT_SPRINT DOA_PHYSICAL_FORM_CHANGE ~SPIN968~
TEXT_SPRINT DJINNI_PHYSICAL_FORM_CHANGE ~SPIN969~
TEXT_SPRINT EFREETI_GAS_FORM_CHANGE ~SPIN970~
TEXT_SPRINT DOA_GAS_FORM_CHANGE ~SPIN971~
TEXT_SPRINT DJINNI_GAS_FORM_CHANGE ~SPIN972~
TEXT_SPRINT AIR_ELEMENTAL_EFFECT ~SPIN973~
TEXT_SPRINT MIND_FLAYER_PSIONIC_BLAST ~SPIN974~
TEXT_SPRINT MIND_FLAYER_DOMINATION ~SPIN975~
TEXT_SPRINT GOLEM_CONFUSION ~SPIN976~
TEXT_SPRINT GOLEM_SLOW ~SPIN977~
TEXT_SPRINT GOLEM_HASTE ~SPIN978~
TEXT_SPRINT GOLEM_GASCLOUD ~SPIN979~

// Class abilities

// Druid

TEXT_SPRINT DRUID_SHAPESHIFT_POLAR_BEAR ~SPCL101~

// Blackguard

TEXT_SPRINT BLACKGUARD_ABSORB_HEALTH ~SPCL102~
TEXT_SPRINT BLACKGUARD_AURA_OF_DESPAIR ~SPCL103~
TEXT_SPRINT RESIST_FEAR ~SPCL104~
TEXT_SPRINT IMMUNITY_TO_LEVEL_DRAIN ~SPCL105~
TEXT_SPRINT BLACKGUARD_ANIMATE_DEAD ~SPCL106~

// Druid

TEXT_SPRINT DRUID_SHAPESHIFT_WINTER_WOLF ~SPCL107~
TEXT_SPRINT DRUID_SHAPESHIFT_BORING_BEETLE ~SPCL108~

// Paladin

TEXT_SPRINT PALADIN_DETECT_EVIL ~SPCL109~

// Druid

TEXT_SPRINT DRUID_SHAPESHIFT_NATURAL_FORM ~SPCL110~

// Paladin

TEXT_SPRINT PALADIN_CURE_DISEASE ~SPCL111~

// Druid

TEXT_SPRINT DRUID_SHAPESHIFT_ELEMENTAL_FIRE ~SPCL112~
TEXT_SPRINT DRUID_SHAPESHIFT_ELEMENTAL_EARTH ~SPCL113~
TEXT_SPRINT DRUID_SHAPESHIFT_ELEMENTAL_WATER ~SPCL114~

// Bard

TEXT_SPRINT BARD_SONG_CURRAN ~SPCL115~
TEXT_SPRINT BARD_SONG_TYMORA ~SPCL116~
TEXT_SPRINT BARD_SONG_KAUDIES ~SPCL117~
TEXT_SPRINT BARD_SONG_SIREN ~SPCL118~
TEXT_SPRINT BARD_SONG_SITH ~SPCL119~
TEXT_SPRINT BARD_SONG_BALLAD ~SPCL120~

// Archer

TEXT_SPRINT ARCHER_CALL_SHOT ~SPCL121~

// Paladin

TEXT_SPRINT PALADIN_SMITE_EVIL ~SPCL122~

// Archer

TEXT_SPRINT ARCHER_KIT_BONUS ~SPCL124~

// Kensai

TEXT_SPRINT KENSAI_KIA ~SPCL144~

// Barbarian

TEXT_SPRINT BARBARIAN_RAGE ~SPCL152~

// Paladin

TEXT_SPRINT PALADIN_LAY_ON_HANDS ~SPCL211~
TEXT_SPRINT PALADIN_PROTECTION_FROM_EVIL ~SPCL212~

// Cavalier

TEXT_SPRINT CAVALIER_REMOVE_FEAR ~SPCL222~

// Inquisitor

TEXT_SPRINT INQUIS_DISPEL_MAGIC ~SPCL231~
TEXT_SPRINT INQUIS_TRUE_SIGHT ~SPCL232~

// Sun Soul Monk

TEXT_SPRINT SUN_SOUL_SUN_SOULRAY ~SPCL236~
TEXT_SPRINT SUN_SOUL_GREATER_SUN ~SPCL237~
TEXT_SPRINT SUN_SOUL_FLAMING_FISTS ~SPCL238~
TEXT_SPRINT SUN_SOUL_SUN_SOULBEAM ~SPCL239~

// Ranger

TEXT_SPRINT RANGER_CHARM_ANIMAL ~SPCL311~

// Berserker

TEXT_SPRINT BERSERKER_RAGE ~SPCL321~

// Beastmaster

TEXT_SPRINT BEASTMASTER_FIND_FAMILIAR ~SPCL342~

// Thief

TEXT_SPRINT SET_SNARE_TRAP ~SPCL412~
TEXT_SPRINT SET_SPECIAL_SNARE_TRAP ~SPCL414~

// Assassin/Blackguard

TEXT_SPRINT ASSASSIN_POISON ~SPCL423~

// Blade

TEXT_SPRINT BLADE_OFFENSIVE_SPIN ~SPCL521~
TEXT_SPRINT BLADE_DEFENSIVE_SPIN ~SPCL522~

// Druid

TEXT_SPRINT DRUID_SHAPESHIFT_BROWNBEAR ~SPCL611~
TEXT_SPRINT DRUID_SHAPESHIFT_WOLF ~SPCL612~
TEXT_SPRINT DRUID_SHAPESHIFT_BLACKBEAR ~SPCL613~

// Totemic Druid

TEXT_SPRINT TOTEMIC_DRUID_SUMMON_SPIRIT_ANIMAL ~SPCL621~

// Avenger

TEXT_SPRINT AVENGER_SHAPESHIFT_SWORDSPIDER ~SPCL632~
TEXT_SPRINT AVENGER_SHAPESHIFT_BABYWYVERN ~SPCL633~
TEXT_SPRINT AVENGER_SHAPESHIFT_FIRESALAMANDER ~SPCL634~

// Shapeshifter

TEXT_SPRINT SHAPESHIFTER_SHAPESHIFT_WEREWOLF ~SPCL643~
TEXT_SPRINT SHAPESHIFTER_SHAPESHIFT_GREATERWEREWOLF ~SPCL644~

// Priest of Talos

TEXT_SPRINT TALOS_STORMSHIELD ~SPCL721~
TEXT_SPRINT TALOS_LIGHTNING_BOLT ~SPCL722~

// Priest of Helm

TEXT_SPRINT HELM_SEEKING_SWORD ~SPCL731~
TEXT_SPRINT HELM_TRUE_SIGHT ~SPCL732~

// Priest of Lathander

TEXT_SPRINT LATHANDER_BOON ~SPCL741~
TEXT_SPRINT LATHANDER_HOLD_UNDEAD ~SPCL742~

// Monk

TEXT_SPRINT MONK_STUNNING_BLOW ~SPCL811~
TEXT_SPRINT MONK_LAY_ON_HANDS ~SPCL815~
TEXT_SPRINT MONK_QUIVERING_PALM ~SPCL820~

// Warrior HLAs

TEXT_SPRINT WARRIOR_WHIRLWIND ~SPCL900~
TEXT_SPRINT WARRIOR_GREATER_WHIRLWIND ~SPCL901~
TEXT_SPRINT WARRIOR_DEATHBLOW ~SPCL902~
TEXT_SPRINT WARRIOR_GREATER_DEATHBLOW ~SPCL903~
TEXT_SPRINT WARRIOR_RESIST_MAGIC ~SPCL904~
TEXT_SPRINT WARRIOR_CRITICAL_STRIKE ~SPCL905~
TEXT_SPRINT WARRIOR_POWER_ATTACK ~SPCL906~
TEXT_SPRINT WARRIOR_HARDINESS ~SPCL907~
TEXT_SPRINT WARRIOR_WAR_CRY ~SPCL908~
TEXT_SPRINT WARRIOR_SMITE ~SPCL909~

// Rogue HLAs

TEXT_SPRINT ROGUE_SET_SPIKE_TRAP ~SPCL910~
TEXT_SPRINT ROGUE_SET_EXPLODING_TRAP ~SPCL911~
TEXT_SPRINT ROGUE_SET_TIME_TRAP ~SPCL912~
TEXT_SPRINT ROGUE_EVASION ~SPCL913~
TEXT_SPRINT ROGUE_GREATER_EVASION ~SPCL914~
TEXT_SPRINT ROGUE_ASSASINATION ~SPCL916~
TEXT_SPRINT ROGUE_AVOID_DEATH ~SPCL917~

// Ranger

TEXT_SPRINT RANGER_TRACKING ~SPCL922~

// Paladin HLA

TEXT_SPRINT PALADIN_SUMMON_DEVA ~SPCL923~

// Druid

TEXT_SPRINT DRUID_IMMUNE_POISON ~SPCL924~
TEXT_SPRINT DRUID_RESISTS ~SPCL925~

// Blackguard HLA

TEXT_SPRINT BLACKGUARD_SUMMON_FALLEN_DEVA ~SPCL935~

// Shadowdancer HLAs

TEXT_SPRINT SHADOWDANCER_SHADOW_TWIN ~SPCL936~
TEXT_SPRINT SHADOWDANCER_SHADOW_MAZE ~SPCL937~
TEXT_SPRINT SHADOWDANCER_SHADOW_FORM ~SPCL938~

// Shaman HLAs

TEXT_SPRINT SHAMAN_SPIRIT_FORM ~SPCL940~
TEXT_SPRINT SHAMAN_FAVORED_OF_THE_SPIRITS ~SPCL941~
