SPRINT BGFORGE_MISC_DIR ~%BGFORGE_LIB_DIR%/misc~

PATCH_IF (GAME_IS ~BG2 TOB BGT BGEE BG2EE EET~) BEGIN PATCH_INCLUDE ~%BGFORGE_MISC_DIR%/scrolls.tpp~ END
PATCH_IF (GAME_IS ~IWDEE~) BEGIN PATCH_INCLUDE ~%BGFORGE_MISC_DIR%/scrolls_iwdee.tpp~ END

PATCH_INCLUDE ~%BGFORGE_MISC_DIR%/opcode.tpp~
PATCH_IF (GAME_IS ~BGEE BG2EE EET IWDEE PSTEE~) BEGIN PATCH_INCLUDE ~%BGFORGE_MISC_DIR%/opcode_ee.tpp~ END

PATCH_INCLUDE
  ~%BGFORGE_MISC_DIR%/scrolls_protection.tpp~
  ~%BGFORGE_MISC_DIR%/icons.tpp~
