TEXT_SPRINT SCROLL_protection_from_acid ~scrl03~
TEXT_SPRINT SCROLL_protection_from_cold ~scrl04~
TEXT_SPRINT SCROLL_protection_from_electricity ~scrl05~
TEXT_SPRINT SCROLL_protection_from_fire ~scrl06~
TEXT_SPRINT SCROLL_protection_from_magic ~scrl07~
TEXT_SPRINT SCROLL_protection_from_poison ~scrl08~
TEXT_SPRINT SCROLL_protection_from_undead ~scrl09~
